### ISSUE TITLE
feature(notifier): add `timeout = 0|false` to keep the notification until manually dismissed

### ISSUE THREAD

**Issue by chrisgrieser** [folke/snacks.nvim#102]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

One common scenario is wanting to keep a notification on screen until manually dismissed via `require("snacks").notifier.hide()`. An ergonomic and intuitive way for doing so would be to have `timeout = 0` (or `timeout = false`) effectively disable the timeout.

This would make `snacks.nvim` also more backwards-compatible with `nvim-notify`, which [also uses `timeout = false` to keep a notification on screen](https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/doc/nvim-notify.txt#L50).

### Describe the solution you'd like

`vim.notify("foobar", vim.log.levels.INFO, { timeout = 0 })` should keep the notification on screen, and `timeout = false` would do the same.

### Describe alternatives you've considered

Using `keep = function() return true end`.

### Additional context

As far as I can tell, `timeout = 0` to keep something on screen is a common practice when designing APIs. [Obsidian notifications, for instance, also work like that.](https://docs.obsidian.md/Reference/TypeScript+API/Notice/(constructor))

**Comment by folke** [comment]
Good idea. Added!

**Comment by chrisgrieser** [comment]
wow, thanks for the quick implementation.

**Comment by chrisgrieser** [comment]
Brief follow-up: I just noticed, it should definitely also support `timeout = false`. Because right now, `timeout = false` does work for nvim-notify and not snacks, and `timeout = 0` works for snacks, but not nvim-notify.

**Comment by folke** [comment]
Added as well.

**Comment by folke** [comment]
And for completeness timeout = true for the default timeout...
