### ISSUE TITLE
feature: Dynamic dashboard text

### ISSUE THREAD

**Issue by OmegaLambda1998** [folke/snacks.nvim#105]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Loving the new dashboard. One of my biggest gripes with other dashboard options is that text is typically fixed on plugin setup. I can add some randomness in the setup but, for instance, if I want my header to reflect my CWD, it won't update as my cwd changes.

### Describe the solution you'd like

Allow dashboard text objects to be a function which are dynamically run when the dashboard is started.

### Describe alternatives you've considered

If you're worried about the performance cost of a callback function, allowing a text object to be associated with a preset action could work too.

**Comment by folke** [comment]
That is already supported.

```lua
{
 {section = "header"},
 function() return {file = vim.uv.cwd()} end
...
}
```

**Comment by folke** [comment]
In fact most of the the builtin sections are generators like that.

**Comment by folke** [comment]
Or to change the header based on cwd:

```lua
function()
 return vim.uv.cwd() == "myspecialdir" and {header = "foobar"} or {section = "header"}
end
```
