### ISSUE TITLE
FR: Indicator for overflow in notification windows

### ISSUE THREAD

**Issue by chrisgrieser** [folke/snacks.nvim#112]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When the notification text is longer than the max height of the notification window, the overflowing text is cut off. 

While this makes sense to prevent windows becoming too large, this creates the problem that I am often not aware that there was text cut off. A notification having only n lines and one having n+ lines are not distinguishable. 

### Describe the solution you'd like

Similar to the `@@@` in vim indicating that there is text outside the viewport, the snacks notifier should somehow indicate if there is text not visible in the notification window, so that the user is aware that they should inspect the window if needed. 

Maybe an indicator icon added to the footer of the window?

### Describe alternatives you've considered

Other than constantly inspecting the notification window, I am not aware of any alternative.

**Comment by folke** [comment]
It seems that floating windows don't respect `lastline` in `display`

**Comment by folke** [comment]
Something like this maybe?

![image](https://github.com/user-attachments/assets/1c9f48ae-131a-4e72-a3ea-1e8f04fc00fb)

**Comment by chrisgrieser** [comment]
yes, displaying a line count instead of just an icon is a great idea
