### ISSUE TITLE
feature: words highlighting only if there are multiple instances

### ISSUE THREAD

**Issue by i40west** [folke/snacks.nvim#117]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I enjoy having the words highlighting, but I find it distracting when it highlights something when there are no other instances of it and thus no use for it. It even highlights string literals.

### Describe the solution you'd like

I'd like an option to have the highlights only show up if there are actually multiple instances.

### Describe alternatives you've considered

It's not a show-stopper.

### Additional context

I'm willing to implement this, but I'm not sure what to call the option or what the cleanest way to do it would be. Probably checking the `get()` result in the autocmd?

**Comment by folke** [comment]
That's tricky, since under the hood we just use `vim.lsp.buf.document_highlight()`.
So `M.get()` will only return the actual count when they are already displayed.
Need to think about this...

**Comment by folke** [comment]
Too much hassle to make this work. Out of scope. Closing
