### ISSUE TITLE
bug: Snacks dashboard can't run command chafa in nushell and pwsh (cmd work fine)

### ISSUE THREAD

**Issue by DwcksDinh** [folke/snacks.nvim#119]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows 11

### Describe the bug

I have updated newest lazyvim with snacks dashboard and use chafa to show image in dashboard, it didn't work if set `vim.o.shell = "pwsh"` or `vim.o.shell = "nu"` at first times:
- nushell:
![image](https://github.com/user-attachments/assets/dbc7da88-5d71-429e-aff4-52a63d13106d)
- powershell:
![image](https://github.com/user-attachments/assets/9054a8fc-e2e3-4364-8bd3-4d3840298104)

- - Error message:
```
   Error  2:24:09 PM notify.error Snacks Terminal **cmd** `chafa "C:\Users\corcl\Pictures\viktor.png" --format symbols --symbols vhalf --size 60x17 --stretch` failed with code `1`:
- `vim.o.shell = "C:\\Users\\corcl\\AppData\\Local\\Programs\\nu\\bin\\nu.exe"`

Output:
[?25l[2J[m[HError:[31m[1Cnu::shell::file_not_found[m[3;1H[31m[2C×[m[1CFile not found
   ╭─[[36m[1m[4msource[m:1:1]
[2m[1C1[22m │ nu
   ·[35m[1m[1C▲[m
   · [35m[1m╰── Could not access file '/s': The system cannot find the file specified. (os error 2)[m
   ╰────[11;1H]0;C:\Users\corcl\AppData\Local\Programs\nu\bin\nu.exe[?25h

```

But if i set `vim.o.shell = "cmd"` it work:
- cmd:
![image](https://github.com/user-attachments/assets/a6c9088c-675c-482a-b3ae-4680c62ed3d0)
Then i change `vim.o.shell = "nu"` dashboard now can show image:
![image](https://github.com/user-attachments/assets/96d367f8-ddaf-4ea0-a3eb-9e9156308d41)

I don't know why, it happen every time when i open terminal.

### Steps To Reproduce

1. Update lazyvim
2. Change dashboard config using chafa cmd
3. It has error when set vim.o.shell = "nu"

### Expected Behavior

Can show image at dashboard while using nushell or powershell 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Check the Neovim docs on how to setup pwsh. Not a snacks issue
