### ISSUE TITLE
bug: Wrong image in terminal.md

### ISSUE THREAD

**Issue by crivotz** [folke/snacks.nvim#12]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0

### Operating system/version

Debian

### Describe the bug

There is the wrong image in [terminal.md](https://github.com/folke/snacks.nvim/blob/main/docs/terminal.md)

### Steps To Reproduce

Show the file

### Expected Behavior

Right image

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
What;s wrong about the image?

**Comment by crivotz** [comment]
Sorry my mistake, I thought the wanted to report also the code above inherent to a possible terminal configuration instead of `Snacks.win`
Instead the purpose was just to show the terminal at the bottom, sorry again
