### ISSUE TITLE
feature: expose terminal management for plugin integrations

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [folke/snacks.nvim#122]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Hi! 
I'm creating my first Neovim plugin (nvim-aider) for Aider integration. Currently, I need to reimplement terminal management logic that already exists in snacks.nvim. Access to the internal terminals table and terminal ID generation would allow better integration and reduce code duplication.

### Describe the solution you'd like

Expose two internal components from snacks.terminal:

    The terminals table storing active terminal instances
    The terminal ID generation logic (either as a function or by exposing the implementation)

This would enable plugins to:

    Track existing terminals without reimplementation
    Generate consistent terminal IDs
    Better integrate with snacks.nvim terminal management

### Describe alternatives you've considered

I'm currently reimplementing this functionality in [nvim-aider](https://github.com/GeorgesAlkhouri/nvim-aider/blob/main/lua/nvim_aider/terminal.lua#L7-L17) as shown in the terminal.lua module. Having access to snacks' internal terminal management would make the integration more robust and maintainable. Also many thanks for the creating of snacks.

**Comment by folke** [comment]
See the updated docs.

```lua
--- Get or create a terminal window.
--- The terminal id is based on the `cmd`, `cwd`, `env` and `vim.v.count1` options.
--- `opts.create` defaults to `true`.
---@param cmd? string | string[]
---@param opts? snacks.terminal.Opts| {create?: boolean}
---@return snacks.win? terminal, boolean? created
function M.get(cmd, opts)
