### ISSUE TITLE
bug: `term_normal` double-escape mapping always sends first escape to terminal

### ISSUE THREAD

**Issue by vandalt** [folke/snacks.nvim#124]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Arch Linux (kernel 6.11.9)

### Describe the bug

When using `snacks.terminal`, the double-escape mapping set in `term_normal` always sends the first escape to the terminal, even if `<esc>` is pressed soon after. I could not find in the docs if this was the expected behavior, but it differs from what happens when using `<C-\><C-n>` directly.

For programs that send text directly to the terminal (e.g. [vim-slime](https://github.com/jpalardy/vim-slime)), this can cause problem if the terminal (or IPython session) is in vi-mode: the shell is in normal mode when you exit, so the first character is interpreted as a vi command by the terminal and therefore not set as an input.

### Steps To Reproduce

1. Use a terminal or IPython session in vi-mode
2. Press escape twice
3. The first escape is sent to the shell, and the shell goes in normal mode

### Expected Behavior

I would have expected the default behavior to be the same as `<C-\><C-n>`, since I could not find a mention of this behavior in the docs.

This behavior can be modified on the user's side by settings `term_normal = false`, and then using a mapping such as `vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>", { desc = "Enter Normal Mode" })` for terminals.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      opts = {},
      keys = {
        { "<c-/>",      function() Snacks.terminal() end, desc = "Toggle Terminal" },
      },
    },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That's how it works. There's no way around it apart from always waiting till ttimeoutlen, which I personally don't like.
You can change it in your own config if you don't like it.

**Comment by 89iuv** [comment]
I have found this to work better and it does not send the first escape to the terminal.

```
    terminal = {
      win = {
        keys = {
          term_normal = {
            "<esc><esc>",
            function()
              return "<C-\\><C-n>"
            end,
            mode = "t",
            expr = true,
            desc = "Double escape to normal mode",
          },
          q = "hide",
          ["<esc>"] = "hide",
        },
      },
```
