### ISSUE TITLE
Feat: Dashboard, in the two panes example suggestion for a better way to enable git

### ISSUE THREAD

**Issue by ChrisGVE** [folke/snacks.nvim#126]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

It is an improvement when neovim is opened within a subfolder of a git project in which there is no `.git` folder existing.

### Describe the solution you'd like

In the example code, the git section is activated by
```lua
enabled = vim.fn.isdirectory(".git") == 1
```

### Describe alternatives you've considered

I implemented a slightly more general code as follows:
```lua
enabled = function()
  local obj = vim.system({ "git", "rev-parse", "--is-inside-work-tree" }):wait()
  return obj.code == 0
end,
```
I don't know if there are better options, but this one works well for me. 

The only caveat is that if `git` is not installed while there is a `.git` folder, the section will remain disabled. I guess that a user without `git` installed wouldn't care.

**Comment by folke** [comment]
even easier is to just do `enabled = Snacks.git.get_root()`.
Either way, not an issue

**Comment by folke** [comment]
nm, `get_root` needs to be fixed to work properly in this case

**Comment by ChrisGVE** [comment]
Cool thanks!
