### ISSUE TITLE
bug(dashboard): bad argument #1 to 'randomseed'

### ISSUE THREAD

**Issue by krishna-bala** [folke/snacks.nvim#135]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

VIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

Ubuntu 22.04

### Describe the bug

After updating to commit [aebffe5](https://github.com/folke/snacks.nvim/commit/aebffe535b09237b28d2c61bb3febab12bc95ae8), launching neovim returns the following error:
```
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/dashboard.lua:10: bad argument #1 to 'randomseed' (number expected, got no value)
stack traceback:
	[C]: in function 'randomseed'
	...cal/share/nvim/lazy/snacks.nvim/lua/snacks/dashboard.lua:10: in main chunk
	[C]: in function 'require'
	...a/.local/share/nvim/lazy/snacks.nvim/lua/snacks/init.lua:26: in function '__index'
	...a/.local/share/nvim/lazy/snacks.nvim/lua/snacks/init.lua:126: in function <...a/.local/share/nvim/lazy/snacks.nvim/lua/snacks/init.lua:123>
```

### Steps To Reproduce

1. Update to the latest commit
2. Try opening dashboard

### Expected Behavior

Dashboard opens.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { dashboard = { enabled = true }, } 
    },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
fixed
