### ISSUE TITLE
feature: GitBrowse opens commit hash

### ISSUE THREAD

**Issue by tonycheang** [folke/snacks.nvim#138]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Hey there, love what you've done with this plugin. As a result, I've been thinking about all my git plugins and realized that I could replace my fugitive workflow with a combination of snacks.lazygit, snacks.gitbrowse, mini.git, and diff.nvim. But there's one feature that I've been missing whose implementation is pretty close to what snacks.gitbrowse already has implemented.

When browsing git logs using git blame line or diffview.nvim, I often want to view the commit on github or at least extract a link for sharing, usually of the form `https://github.com/{org}/{repo}/commit/{commit_hash}`.

### Describe the solution you'd like

One solution I've toyed with is when the cursor is on a line `commit {HASH}` at the top of some git log entry, `Snacks.gitbrowse.open()`, should open that commit. I don't know if there's a more elegant or general solution, and I'm certainly open to alternatives and better solutions :)

### Describe alternatives you've considered

If this behavior seems pretty bespoke, some options API for adding user defined fields / what's and a way to provide such a field to `_open` would work for me. Beyond branch and file, I'd add `commit` and provide the commit hash via a function to parse the current line / context from my cursor or something similar.

**Comment by krishna-bala** [comment]
My current workflow:
1. Find the commit id you're interested in viewing on github
    - For me, `<cmd>Gitsigns blame<CR>` and then yank the commit hash
2. Open Lazygit Log (default: `<leader>gl`)
3. Enter Search mode (`/`) and paste (`<C-Shift-v>`) the commit hash (note: may take a few seconds to load really old commits if git history is large).
4. Open commit in browser (`o` keybinding in lazygit)

**Comment by dpetka2001** [comment]
@tonycheang @krishna-bala Would appreciate if you could test #161. 

I don't parse the whole line (as I think that would be more complicated and more edge cases to possibly take into account). I just check the current word under the cursor if it's a valid commit hash, so your cursor would have to be on top of a valid commit hash. 

I checked with `diffview` current file history and `gitsigns` blame buffer and it worked in my tests. Not sure if I've missed some other case.

**Comment by krishna-bala** [comment]
This works for me with repos hosted on github (e.g. `snacks.nvim`).

Side note: This doesn't work for repos not on github/gitlab (e.g. bitbucket) -- that's expected though, as `url_patterns` only contains patterns for github and gitlab.

Adding the following entry to `url_patterns` enables this for `bitbucket` as well, though that should probably go in a separate pull request.

```lua
  url_patterns = {
    ["github%.com"] = {
      branch = "/tree/{branch}",
      file = "/blob/{branch}/{file}#L{line}",
      commit = "/commit/{commit}",
    },
    ["gitlab%.com"] = {
      branch = "/-/tree/{branch}",
      file = "/-/blob/{branch}/{file}#L{line}",
      commit = "/-/commit/{commit}",
    },
    ["bitbucket%.org"] = {
      branch = "/src/{branch}",
      file = "/src/{branch}/{file}#lines-{line}",
      commit = "/commits/{commit}",
    },
  },
```

**Comment by tonycheang** [comment]
Oh nice! That works for my diffview workflow, git blame line one, as well as a few others where it's not explicitly a git log. TIL `git rev-parse --verify {hash}` too, thanks :).

**Comment by dpetka2001** [comment]
@krishna-bala I don't use bitbucket so I can't test this, but I believe you can already extend the `url_patterns` in your personal configuration with something like 
```lua
{
  "folke/dashboard.nvim",
  opts = {
    gitbrowse = {
      url_patterns = {
        ["bitbucket%.com"] = {
          -- your own settings here
        },
      },
    },
  },
}
```
So, I'm not really sure if a separate PR would be in order, since `gitbrowse` was made to be extensible in the user's personal configuration and clearly not everything can be included in the defaults. Except if I'm mistaken about `gitbrowse`'s extensibility.

@tonycheang I also found about `git rev-parse --verify` today. Google is a great friend :smile:

**Comment by krishna-bala** [comment]
@dpetka2001 you are correct, extending the `url_patterns` in my user config (e.g. `lua/plugins/snacks.nvim`) works just fine. I'm going to leave open the [pull request](https://github.com/folke/snacks.nvim/pull/163) for adding `bitbucket%.org` as a `url_pattern` for now in case that seems like a sensible default.

**Comment by dpetka2001** [comment]
@krishna-bala I'm just a simple user like you and not insinuating you shouldn't make a PR for it. I thought you were referring to me to create a separate PR when i first read your comment before you created your own PR. Thus my previous answer was purely about my thought process that you can already extend `url_patterns`. It was not meant towards you as a remark that you should not make a PR. I hope there was no misunderstanding and didn't offend you.

**Comment by krishna-bala** [comment]
Haha no you didn't offend me :) I didn't even think about adding it to my user config! I appreciate the follow up -- you've been a huge help across the board on plugins / LazyVim, so thank you!
