### ISSUE TITLE
feature: open dashboard in new tab

### ISSUE THREAD

**Issue by linsui** [folke/snacks.nvim#145]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When LazyVim uses dashboard.nvim I was able to do this with

```lua
 vim.api.nvim_create_autocmd("TabNewEntered", {
   callback = function()
     require('dashboard'):instance()
   end,
 })
 ```

but this doesn't work because it open the dashboard in a float window.

```lua
 vim.api.nvim_create_autocmd("TabNewEntered", {
   callback = function()
     Snacks.dashboard()
   end,
 })
 ```

How can I do the same thing? Thanks!

### Describe the solution you'd like

I want a function to open the dashboard in new tab, similiar to what it does when open nvim.

### Describe alternatives you've considered

No idea

**Comment by folke** [comment]
This was actually already possible with:

```lua
vim.api.nvim_create_autocmd("TabNewEntered", {
  callback = function()
    Snacks.dashboard({
      buf = vim.api.nvim_get_current_buf(),
      win = vim.api.nvim_get_current_win(),
    })
  end,
})
```

Just made a small change that you can also pass `0` in this case.

```lua
vim.api.nvim_create_autocmd("TabNewEntered", {
  callback = function()
    Snacks.dashboard({ buf = 0, win = 0 })
  end,
})
```

**Comment by linsui** [comment]
Thanks!
