### ISSUE TITLE
bug: dashboard startuptime incorrect

### ISSUE THREAD

**Issue by SuXYIO** [folke/snacks.nvim#149]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

MacOS 12.7.5

### Describe the bug

When opened with `nvim` from shell, the startup time shows `0ms`.  
![Snipaste_2024-11-23_14-12-11](https://github.com/user-attachments/assets/92e2fcb5-607c-4554-a12b-271d6a3748bb)

When opened with `lua Snacks.dashboard.open()` in nvim cmd mode, it shows the correct time.  
![Snipaste_2024-11-23_14-12-20](https://github.com/user-attachments/assets/79f78e58-86c7-4ec3-aa80-9812cde0c932)

Also, is there a way to change the `startup` icon like other sections? 

My snacks config
```lua
return {'folke/snacks.nvim',
	event = 'VimEnter',
	dependencies = 'nvim-tree/nvim-web-devicons',
	opts = {
		bigfile = { enabled = true, notify = true },
		dashboard = {
			enabled = true,
			sections = {
				{ section = 'header' },
				{ section = 'keys', gap = 1, padding = 1 },
				{ section = 'startup' },
				{ pane = 2, icon = " ", title = "Recent Files", section = "recent_files", indent = 2, padding = 1 },
				{ pane = 2, icon = " ", title = "Projects", section = "projects", indent = 2, padding = 1 },
			},
			preset = {
				keys = {
					{ icon = " ", key = "r", desc = "Recent Files", action = ":lua Snacks.dashboard.pick('oldfiles')" },
					{ icon = " ", key = "f", desc = "Telescope", action = ":Telescope" },
					{ icon = "󰒲 ", key = "L", desc = "Lazy", action = ":Lazy", enabled = package.loaded.lazy ~= nil },
					{ icon = " ", key = "c", desc = "Config", action = ":lua Snacks.dashboard.pick('files', {cwd = vim.fn.stdpath('config')})" },
					{ icon = " ", key = "q", desc = "Quit", action = ":qa" },
				},
				header =
[[
 _______             ____   ____.__         
 \      \   ____  ___\   \ /   /|__| _____  
 /   |   \_/ __ \/  _ \   Y   / |  |/     \ 
/    |    \  ___(  <_> )     /  |  |  Y Y  \
\____|__  /\___  >____/ \___/   |__|__|_|  /
        \/     \/                        \/ 
]]
			},
		},
		notifier = { enabled = true },
		lazygit = { enabled = true, configure = true },
	},
	keys = {
		{ "<Leader>d", function() Snacks.lazygit() end },
	}
}
```

### Steps To Reproduce

1. Config the snacks dashboard with a startup section
1. Enter `nvim` in shell

### Expected Behavior

The startup time is `0ms`

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
You're lazy-loading snacks on `VimEnter`. Please use the suggested setup.
Things like `bigfile` simply can't work if you lazy-load on `VimEnter`.

**Comment by SuXYIO** [comment]
Sorry bro, my bad. It works now.
