### ISSUE TITLE
bug: layout shift of status column

### ISSUE THREAD

**Issue by zvrkSam** [folke/snacks.nvim#150]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

I found this by accident and I have tested this on a fresh install of Lazyvim.

![Screenshot from 2024-11-23 08-39-45](https://github.com/user-attachments/assets/bb3f7c02-c4f7-412f-8f65-0856609b0380)

This is a rare case, but its out there, just to let you know.

### Steps To Reproduce

1. visually select more then one line of text
2. press i
3. after second or two the status column will shift

### Expected Behavior

I think it should not layout shift

**Comment by folke** [comment]
Can't reproduce and pretty sure this is not caused by snacks.
The fact that your statuscolumn, shows the config option itself is not normal.
Some plugin seems to change the statuscolumn value and tries including the old value, but in a wrong way

**Comment by mertzt89** [comment]
I also encountered this, you might need to set status column as follows:
```lua
 vim.o.statuscolumn = [[%!v:lua.require'snacks.statuscolumn'.get()]]
```

**Comment by folke** [comment]
That's what I mean. Snacks already does that.
I think another plugins tries to update your statuscolumn by adding something extra, but does it incorrectly.

**Comment by mertzt89** [comment]
Not sure what I had wrong before, but I removed manually setting `vim.o.statuscolumn` in my config and things are working as expected. If the issue comes up again, I'll investigate to see where the conflicting configuration is.

**Comment by zvrkSam** [comment]
I double checked this, deleted everything related to neovim, and installed a fresh a fresh copy of lazyvim where there are no plugins, I'm still seeing this. But this is a very very rare case anyways, I just wanted to let you know.

**Comment by folke** [comment]
might also be a bug in Neovim then...

**Comment by folke** [comment]
Damn, I **can** also reproduce it now, but in my case it doesn't show that text.
It does shift the width of the statuscolumn though.
Will check what's happening here...

**Comment by folke** [comment]
```
  statuscolumn=
	Last set from error handler
```

**Comment by folke** [comment]
The poblem is noice + notifier + mini.ai + ui_attach weirdness.
`i` triggers an expr keymap for `mini.ai`.
After 1 second, `mini.ai` echo's a message that gets picked up by Noice
and eventually by Snacks.

Since it's an expr keymap, textlock is active, so it's not possible for notifier to render the message.
That triggered an error and somehow was part of the statuscolumn stacktrace, which failed and messed up the statuscolumn.

Added better handling of `E565` errors to notifier / win & statuscolumn.

Will work now, but the `mini.ai` help message will be shown too late....

**Comment by folke** [comment]
@luukvbaal, do you have any ideas?

**Comment by serafimqwe** [comment]
I am having the same issue on neovim v.0.11.3 with LazyVim latest version
