### ISSUE TITLE
bug: Notifier closes window created by nvim-treesitter-context

### ISSUE THREAD

**Issue by jblsp** [folke/snacks.nvim#160]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 14.4

### Describe the bug

Notifications created by the Notifier snack cause the nvim-treesitter-context window to close. This is especially bad when using Notifier to display LSP progress with Notifier and nvim-treesitter-context enabled.

### Steps To Reproduce

1. Open a code file that is scroll-able to display a nvim-treesitter-context window.
2. Run a test notification `:lua vim.notify("test")`

### Expected Behavior

The notifier window should display above the nvim-treesitter-context window (this is how nvim-notify by rcarriga handles it)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { notifier = { enabled = true } } },
    { "nvim-treesitter/nvim-treesitter-context" },
  },
})
```

**Comment by folke** [comment]
That's a bug in the nvim-treesitter-context code. See this line: https://github.com/nvim-treesitter/nvim-treesitter-context/blob/8e412ebe97d84504b68a071ecf9bb68413b13632/lua/treesitter-context.lua#L192

It should check that the event was triggered by the buffer where the context is being displayed.

not a snacks issue
