### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by WartClaes** [folke/snacks.nvim#165]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 15.0.1

### Describe the bug

Snacks dashboard does not open when starting a new nvim instance.

When I run `:checkhealth snacks` it shows the following response:

```
Snacks.dashboard
- OK setup {enabled}
- OK setup ran
- WARNING dashboard did not open: argc(-1) > 0
```

I'm using iTerm as the terminal app.

It does work when using `:lua Snacks.dashboard()`

### Steps To Reproduce

open nvim

### Expected Behavior

dashboard should be visible

### Repro

```lua
{
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
      dashboard = {
        enabled = true,
      },
    },
  }
```

**Comment by folke** [comment]
How are you starting Neovim? If there's any arg, then the dashboard won't load, which is what happened in this case

**Comment by WartClaes** [comment]
I use `nvim .` to open my current folder. But maybe I need to start learning on removing the directory 🙈 

Although it might be nice to be able to see it when opening a specific folder?

**Comment by folke** [comment]
If you do `nvim .` then you're opening the directory, in which case the dashboard should not be shown.
