### ISSUE TITLE
feature: change the default notifier style

### ISSUE THREAD

**Issue by fpohtmeh** [folke/snacks.nvim#166]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

The notifier module is designed to replace older notification plugins.
However, it introduces a new style with the icon and the notification type at the top. It looks untypical; I didn't see a similar appearance earlier.

Other provided styles are better but I didn't find them good for myself

### Describe the solution you'd like

Use some default or popular style from the replaced plugin(s)

### Describe alternatives you've considered

A few alternatives:
1. Use fancy style by default - it's more familiar for users
2. Use minimal but bordered as the default one
3. Provide the following style
![image](https://github.com/user-attachments/assets/cc0beaa0-89be-4c71-bb08-8fcea2988c01)

### Additional context

Just an idea for the future: it may be cool to have configurable sections/panes like in the snacks dashboard

**Comment by folke** [comment]
You can implement your own style. 
I like the `compact` default and will keep it that way.
I don't see why the snacks notifier should look like nvim-notifier or other options...

**Comment by fpohtmeh** [comment]
Found it in the `Snacks.config.style` section. Thank you
