### ISSUE TITLE
bug: attempt to concatenate field 'name' (a nil value)

### ISSUE THREAD

**Issue by Allaman** [folke/snacks.nvim#167]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-ff93cccbc

### Operating system/version

macOS 14.7

### Describe the bug

Hello,

thanks for another great plugin. I recognized a bug introduced by https://github.com/folke/snacks.nvim/commit/6e3cb7e53c0a1b314203d392dc1b7df8207a31a6

Error:
<img width="1547" alt="image" src="https://github.com/user-attachments/assets/307723ef-c204-4c36-bfee-b0e06e0bd75c">

### Steps To Reproduce

Minimal not working config:

```lua
-- From https://github.com/folke/lazy.nvim
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/snacks.nvim",
    commit = "6e3cb7e53c0a1b314203d392dc1b7df8207a31a6",
    init = function()
      vim.api.nvim_create_autocmd("User", {
        pattern = "VeryLazy",
        callback = function()
          Snacks.toggle.option("spell", { name = "Spelling" }):map("<leader>ts")
        end,
      })
    end,
  },

  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

Uncommenting `Snacks.toggle.option("spell", { name = "Spelling" }):map("<leader>ts")` prevents the error.

### Expected Behavior

To be able to use the callback for defining toggles in the autocmd

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Fixed. Thank you for reporting!
