### ISSUE TITLE
feature: support function type in `sections.cmd`

### ISSUE THREAD

**Issue by rogtino** [folke/snacks.nvim#168]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to show some todo entries with orgmode in dashboard.
Currently this won't work:
```lua
{
  section = "terminal",
  cmd = function()
      local api = require("orgmode.api")
      local files = api.load()
      local today_all = 0
      local today_todo = 0
      for _, file in ipairs(files) do
          for _, headline in ipairs(file.headlines) do
              if headline.deadline and headline.deadline:is_today() then
                  if headline.todo_type == "DONE" then
                      today_todo = today_todo + 1
                  end
                  today_all = 1 + today_all
              end
          end
      end
      return " " .. today_todo .. "/" .. today_all
  end,
  gap = 1,
  padding = 1,
  title = "Orgs",
  icon = "",
},

```

### Describe the solution you'd like

support cmd function would be great

### Describe alternatives you've considered

I can't figure out another alternative using usercommand or external command.

**Comment by folke** [comment]
That is already support. Just add a function without the ` cmd =`
