### ISSUE TITLE
feature: not focusable notifications by default

### ISSUE THREAD

**Issue by fpohtmeh** [folke/snacks.nvim#174]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I use <C-w>w to switch between windows when there is a single split. However, notifications steal the focus and break this behaviour.
There is no value in the focusing on the notification since it quickly closes and user has no time to perform copying or other operation

### Describe the solution you'd like

Make notifications not focusable by default. Potential solution:
```
    styles = {
      notification = {
        on_win = function(win)
          vim.api.nvim_win_set_config(win.win, { focusable = false })
        end,
      },
    },
```

### Describe alternatives you've considered

Alternatively, add a new option to snacks.win options to make the work with focus more convenient

### Additional context

Thank you for the delicious snacks

**Comment by fpohtmeh** [comment]
Damn, thank you. Do you agree to make it false by default?

**Comment by dpetka2001** [comment]
I'm just a simple user like you. I don't make any decisions for this project. 

In my personal opinion as a simple user, I think that this is down to personal preference at the end and since this is configurable users can do whatever they want in their personal configuration.

**Comment by folke** [comment]
I want to keep it focusable by default.
Focusing a notification prevents it from disappearing and it's of course useful to yank content
