### ISSUE TITLE
feature: hide lsp hover info

### ISSUE THREAD

**Issue by HymanZHAN** [folke/snacks.nvim#175]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

In noice, there is an option `opts.lsp.hover.silent = true`, which is useful for cases where multiple language servers are attached to a file and not all of them can provide hover info. Now with snacks, there seem to be no such option yet.

### Describe the solution you'd like

Provide a similar option like `opts.lsp.hover.silent`

### Describe alternatives you've considered

Overriding `vim.lsp.handlers["textDocument/hover"]` so that empty messages are not sent. It works, but if an option like `opts.lsp.hover.silent` can be provided, the config will be a tad cleaner.

**Comment by folke** [comment]
That is not related to snacks and should still be filtered with noice if you use the sncaks notifier as the notify backend in noice

**Comment by HymanZHAN** [comment]
Sorry I am pretty new to NeoVim plugins, and I am a bit confused. May I ask what the configuration of LazyVim 13 is? Because after updating to 13, even though I have `opts.lsp.hover.silent = true` set for `noice`, I still see multiple empty notifications shown.

![Screenshot from 2024-12-01 18-14-51](https://github.com/user-attachments/assets/0a09f361-0710-4f9c-962c-ae47704fc39d)

**Comment by sirjager** [comment]
facing the same issue

![image](https://github.com/user-attachments/assets/99781d8b-0d35-4d0f-89e4-7a347bcc4cfc)

**Comment by sirjager** [comment]
I was facing same issue, @HymanZHAN 
below tweaks, stopped these notifications

![image](https://github.com/user-attachments/assets/214a8192-94f4-4bae-9983-4b3ee76124b5)

**Comment by HymanZHAN** [comment]
Thanks, I'll give it a try.
