### ISSUE TITLE
feature: Extend the default opts when calling Snacks.scratch()

### ISSUE THREAD

**Issue by Jendker** [folke/snacks.nvim#179]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When toggling the scratch window I'd like to use the current filetype. To this end I'm doing:
`{ "<leader>.", function() require("snacks").scratch({ ft = vim.bo.filetype }) end, desc = "Toggle Scratch Buffer" }`
This doesn't work, more context below.

### Describe the solution you'd like

It seems to me that the passed opts are not merged with the default ones. Can that be considered?

### Describe alternatives you've considered

Change snacks.nvim to always default to the current buffer type.

### Additional context

When I'm currently using this keymap, I'm getting an error:
```
E5108: Error executing lua: ...local/share/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:180: Invalid 'text': Expected Lua string
stack traceback:
        [C]: in function 'nvim_strwidth'
        ...local/share/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:180: in function 'open'
        /Users/jedrzej/.config/nvim/lua/plugins.lua:1684: in function </Users/jedrzej/.config/nvim/lua/plugins.lua:1684>
```

**Comment by folke** [comment]
What are you using for icons?

Either way, try again, should work now, but you won't get a python icon I guess

**Comment by folke** [comment]
I've just pushed some changes with better support for nvim-web-devicons.
So you should also see the python icon now.

**Comment by Jendker** [comment]
Oh, I see now what's happening, my bad.
The filename is `~/.local/share/nvim/scratch/1_%7C_%7CScratch_%7C_%2FUsers_%2Fjedrzej_%2FProjects_%2Frobonetv3_%7Cmain.python`
Notice the file extension. Looks like a mapping would be needed from the filetype to the extension. I'm not sure if that is something I need to take care about to pass as the `ft` argument to the `Snacks.scratch(...)` call or if that's something what can happen internally in Snacks.

**Comment by folke** [comment]
that should actually work as is, although not ideal :)

But a file with extension `markdown` or `python` gets the proper filetype.
update snacks and try again. should properly show as python

**Comment by Jendker** [comment]
That's great, thank you for committing your time for this! The icon works fine now both in lua and python.
If I'm using my snippet from above I am not getting LSP or treesitter in the python scratch window, because the file extension is wrong (.python instead of .py), but the scratch window is still extremely helpful! I appreciate your help.

**Comment by folke** [comment]
Should also attach treesitter and LSP now :)

**Comment by Jendker** [comment]
That's amazing! It's all I could have asked for. I appreciate your time, Folke!
