### ISSUE TITLE
feature: arrange section keys items horizontally

### ISSUE THREAD

**Issue by shy-robin** [folke/snacks.nvim#180]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Currently, section keys items aligns vertically like below:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/494c89b2-d0d5-4dec-b4c2-a107e1efaf85">
I feel like it's too spacious.

### Describe the solution you'd like

Is it possible to put then in a row like dashboard-nvim ?
<img width="979" alt="image" src="https://github.com/user-attachments/assets/5db04493-e47f-45d9-b4b5-6e721991e064">

### Describe alternatives you've considered

empty

**Comment by folke** [comment]
You can add `hidden=true` to the keymaps and then use a custom text section at the top.

See https://github.com/folke/snacks.nvim/discussions/111 for some examples.
