### ISSUE TITLE
bug: dashboard will move right automatically after startup

### ISSUE THREAD

**Issue by shy-robin** [folke/snacks.nvim#182]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 13.0

### Describe the bug

[

https://github.com/user-attachments/assets/ff133d7b-b018-4533-9e72-27089416e91c

](url)

### Steps To Reproduce

1. startup
2. dashboard will move right automatically after startup

I think it's because of signcolumn.
I use `luukvbaal/statuscol.nvim` and `neoclide/coc.nvim`, they both set signcolumn.
When I disable them, the issue disappears.

### Expected Behavior

I hope dashboard keep still.

**Comment by folke** [comment]
snacks already sets `signcolumn=no` and `statuscolumn=""`.
If another plugin overrides that, then it should be disabled on the snacks dashboard.
not a snacks issue...
