### ISSUE TITLE
bug: Scratchpad file names are to long for dashboard recent files

### ISSUE THREAD

**Issue by zvrkSam** [folke/snacks.nvim#183]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

![Screenshot from 2024-12-01 18-09-30](https://github.com/user-attachments/assets/19b48189-3f0a-4ead-bbe5-c7bd7a7c2f17)

How would you feel about truncating the long file names so it doesn't break the alignment ?

### Steps To Reproduce

I opened scratch pad in different directories

### Expected Behavior

Would be nicer if file names weren't so long

**Comment by folke** [comment]
Fixed and additionally I also exclude files from stdpaths in recent files lists.
