### ISSUE TITLE
feature(dashboard): hide recent_files section title when the list is empty

### ISSUE THREAD

**Issue by benelan** [folke/snacks.nvim#184]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I have the following section in my dashboard config:

```lua
{
  title = "Recent Files",
  section = "recent_files",
  cwd = true,
  indent = 2,
},
```

When I'm in a new project and there are no recent files for the cwd, it would be nice if the title was hidden.

### Describe the solution you'd like

Hide the `recent_files` section's title if the length of the recent files list is 0. I think it makes sense as the default, but it could also be a boolean option.

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
Makes sense. Added!
