### ISSUE TITLE
bug: (notifier) Can't change `notifier.show_history()` float window title and border highlights.

### ISSUE THREAD

**Issue by polirritmico** [folke/snacks.nvim#185]
### Describe the bug

Hi. I was adding support for Snacks in [my colorscheme](https://github.com/polirritmico/monokai-nightasty.nvim), but I couldn't get the highlight groups for the `notifier.show_history()` float window title and border:

> ![2024-12-01_171804](https://github.com/user-attachments/assets/dc783181-c248-4dd8-a649-69ca7a66ef34)

Here I'm using this **undocumented** hl groups, but none of them affects the float window title and/or border:

```lua
local test_hl = { fg = "#ff00ff", bg = "#00ff00" }
local ret = {
  -- etc.
  SnacksNotifierHistory = test_hl, -- Float window Normal
  SnacksNotifierHistoryDateTime = test_hl, -- Dates in entries
  SnacksNotifierHistoryTitle = test_hl, -- Changes the `Snacks` text for each log entry 
}
```

---

Maybe related to [this line](https://github.com/folke/snacks.nvim/blob/5f768f8584e5247e3283201bfa068fa394ed0c4b/lua/snacks/notifier.lua#L98):

```lua
Snacks.config.style("notification.history", {
  -- etc.
  wo = { winhighlight = "Normal:SnacksNotifierHistory" },
})
```

For example, if changed to something like:

```lua
wo = {
  winhighlight = "Normal:SnacksNotifierHistory,FloatBorder:SnacksNotifierHistoryBorder,FloatTitle:SnacksNotifierHistoryTitle",
},
```

Then I could change the border and title:

![2024-12-01_172505](https://github.com/user-attachments/assets/a786718d-6f7f-4076-9fdd-4f0dc627e047)

### Expected behavior

On my first approach I was expecting that the float border/title follows `SnacksNormal`. I don't know if that could be the appropriate hl or not, but it would be great if this could be adjusted, specially for floating windows bg transparency and related settings.

**Comment by folke** [comment]
those undocumented groups are used to render the notifications themselves and have nothing to do with the title.
You can indeed just override the winhl for the notification history
