### ISSUE TITLE
bug: Scratch buffer error saving with markdown

### ISSUE THREAD

**Issue by Redoxahmii** [folke/snacks.nvim#187]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

Creating scratch buffer with `ft="markdown"` does not save if you `ctrl + s` but gives error for an autocmd.
if you set it as `ft="md"` then it does not recognize the file as markdown nor does it start the LSP or highlighting but saves correctly.

### Steps To Reproduce

1. set `ft = "markdown"` for scratch.
2. open buffer and `ctrl + s`.

### Expected Behavior

Should not error out for the autocmd.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That's a bug in conform.nvim https://github.com/stevearc/conform.nvim/blob/a203480a350b03092e473bf3001733d547160a73/lua/conform/runner.lua#L492

That line needs to change `basename` to `basename:gsub("%", "%%")`

**Comment by folke** [comment]
Closing, since it's upstream
