### ISSUE TITLE
feature(dashboard): Allow terminal section to have an action

### ISSUE THREAD

**Issue by RUGMJ** [folke/snacks.nvim#189]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to be able to add a keybind to a terminal section

### Describe the solution you'd like

Being able to do something like this:
```lua
{
          title = "Notifications",
          cmd = "gh notify -s -a -n5",
          icon = " ",
          section = "terminal",
          action = function()
            vim.ui.open("https://github.com/notifications")
          end,
          key = "N",
        }
 ```

### Describe alternatives you've considered

Manually adding a new bind for the ft but this is cumbersome

**Comment by folke** [comment]
Your example should work as expected now.

**Comment by RUGMJ** [comment]
Wow that was quick; it allows me to scroll down and press enter to trigger the action but it seems the keybind isn't being registered still?

**Comment by folke** [comment]
I took some shortcuts. Need to change it properly. Will do so later today

**Comment by folke** [comment]
I properly added this functionality now.

When a section has an action/key and also a title, it will be added to the title.
Otherwise it's added to the section.

If you don't want to see the `key` at the end of the title, additionally add `label = "'`

**Comment by folke** [comment]
I just updated the github example: https://github.com/folke/snacks.nvim/blob/main/docs/dashboard.md#github

![image](https://github.com/user-attachments/assets/6a6b7b94-248c-4971-ba52-fcaef3173d69)

**Comment by RUGMJ** [comment]
Awesome, thank you so much for the rapid response time
