### ISSUE TITLE
bug(scratch): Can't run line selected with visual line select from scratch buffer

### ISSUE THREAD

**Issue by ibutra** [folke/snacks.nvim#190]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 10

### Describe the bug

When selecting a whole line in visual line mode (Shift+v) and then pressing Enter a **Column index is too high** error is shown in 
`debug.lua:56`

### Steps To Reproduce

1. Open a scratch buffer with filetype lua (default)
2. enter `vim.print(Snacks.notifier.get_history())`
3. with the cursor on the previously entered line hit <Shift+v>
4. Hit Enter
5. ~Profit~ Observe error

### Expected Behavior

Execute only this line

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I can't reproduce this with:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
      notifier = {},
    } },
    -- add any other plugins here
  },
})

vim.schedule(function()
  Snacks.notify("test")
  Snacks.scratch({ template = [[vim.print(Snacks.notifier.get_history())]] })
end)
```

Save as `repro.lua` and run with `nvim -u repro.lua`.

Does the repro run ok for you?

Are you 100% sure you are using the latest version of Snacks?
Do you have any weird keymaps related to visual selection?

**Comment by shy-robin** [comment]
> I can't reproduce this with:
> 
> ```lua
> vim.env.LAZY_STDPATH = ".repro"
> load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
> 
> require("lazy.minit").repro({
>   spec = {
>     { "folke/snacks.nvim", opts = {
>       notifier = {},
>     } },
>     -- add any other plugins here
>   },
> })
> 
> vim.schedule(function()
>   Snacks.notify("test")
>   Snacks.scratch({ template = [[vim.print(Snacks.notifier.get_history())]] })
> end)
> ```
> 
> Save as `repro.lua` and run with `nvim -u repro.lua`.
> 
> Does the repro run ok for you?
> 
> Are you 100% sure you are using the latest version of Snacks? Do you have any weird keymaps related to visual selection?

@folke I meet the same issue.

1. I select a line:
<img width="877" alt="image" src="https://github.com/user-attachments/assets/910baf24-ced6-4547-96c2-e7708df730f3">
2. When I hit Enter, it occurs error:
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/d12f9d1f-a13a-4e99-aacb-b83887fe723b">

**Comment by folke** [comment]
@shy-robin and with the repro?

**Comment by ibutra** [comment]
With the repo I can reproduce it but it still takes manual steps.
After loading the repo I get a big error regarding missing treesitter grammar but after dismissing that and then executing `:lua Snack.scratch()` and in there entering some lua again and selecting the line with `Shift+v` again and hitting enter I get the initially mentioned error. If needed I can try to make a screen recording of it.

No mappings for visual selection. And I just installed Snacks today through lazy so I am pretty confident it is the latest version.

**Comment by folke** [comment]
That missing treesitter grammar is NOT normal, since the lua treesitter parser is included in Neovim.
What Neovim version are you using? If you build it yourself, then it means your runtime is messed up.

**Comment by folke** [comment]
Do you set `vim.o.selection` by any chance?
I also just pushed an update to get the visual selection in a different way.
Can you check if that fixes it?

**Comment by shy-robin** [comment]
> @shy-robin and with the repro?

My repo: https://github.com/shy-robin/shy-nvim

I have updated the Snacks.nvim , but the error still exists.

```
E5108: Error executing lua: .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/debug.lua:61: Column index is too high
stack traceback:
	[C]: in function 'nvim_buf_get_text'
	.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/debug.lua:61: in function 'run'
	...local/share/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:58: in function <...local/share/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:56>

```

**Comment by folke** [comment]
@shy-robin can you please use the repro instead and see what that does?

**Comment by ibutra** [comment]
`vim.o.selection` is set to `inclusive` so the default.

The treesitter error was on a different system, apologies for that I shouldn't mix the systems while trying to reproduce so now I am back to the windows system where I observed this behaviour initially.

Sadly on this system I get this error on startup with your repo:
```
Error executing vim.schedule lua callback: ...o/data/nvim-data/lazy/snacks.nvim/lua/snacks/scratch.lua:235: attempt to index field 'keys' (a nil value)
stack traceback:
	...o/data/nvim-data/lazy/snacks.nvim/lua/snacks/scratch.lua:235: in function 'scratch'
	C:\Users\RAS3ABT\Desktop\tmp\repro.lua:15: in function <C:\Users\RAS3ABT\Desktop\tmp\repro.lua:13>
```

after this error, sadly the scratch buffer is not set to lua filetype anymore and I can't execute its content at all.

Seems to me this has to do with setting a mapping for R in case a template was given so I removed the template for the scratch buffer in repro and tried again.

But now I still don't get the default mapping vor `<CR>` to execute in the scratch buffer.
While here I noticed q doesn't close the scratch buffer in visual line mode, would be nice if it did.
Is there a way to force the scratch buffer to be a lua buffer?

What I did notice though is, that here in the scratch buffer when using visual line mode it ends on the last character of the line while in my normal nvim configuration it ends one after the line. Sadly I am not aware of a change I did to change this behavior.

**Comment by shy-robin** [comment]
> I can't reproduce this with:
> 
> ```lua
> vim.env.LAZY_STDPATH = ".repro"
> load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
> 
> require("lazy.minit").repro({
>   spec = {
>     { "folke/snacks.nvim", opts = {
>       notifier = {},
>     } },
>     -- add any other plugins here
>   },
> })
> 
> vim.schedule(function()
>   Snacks.notify("test")
>   Snacks.scratch({ template = [[vim.print(Snacks.notifier.get_history())]] })
> end)
> ```
> 
> Save as `repro.lua` and run with `nvim -u repro.lua`.
> 
> Does the repro run ok for you?
> 
> Are you 100% sure you are using the latest version of Snacks? Do you have any weird keymaps related to visual selection?

With this repro, after running `nvim -u repro.lua`, it occurs error:
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/25198f77-279f-4e40-bb4d-5328afe5775f">

```
Error executing vim.schedule lua callback: ....repro/data/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:235: attempt to index field 'keys' (a nil value)
stack traceback:
        ....repro/data/nvim/lazy/snacks.nvim/lua/snacks/scratch.lua:235: in function 'scratch'
        /Users/shyrobin/.config/nvim/repro.lua:15: in function </Users/shyrobin/.config/nvim/repro.lua:13>
```

**Comment by folke** [comment]
That keys error is weird, but just fixed that.
For some reason I don't get that error... Seems that in your case, filetype detection did not yet run for some reason.

Can you both try again with this update repro?

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
      notifier = {},
    } },
    -- add any other plugins here
  },
})

vim.schedule(function()
  Snacks.notify("test")
  Snacks.scratch({ ft = "lua", template = [[vim.print(Snacks.notifier.get_history())]] })
end)

**Comment by folke** [comment]
> What I did notice though is, that here in the scratch buffer when using visual line mode it ends on the last character of the line while in my normal nvim configuration it ends one after the line. Sadly I am not aware of a change I did to change this behavior.

That's what I was thinking of. This can only be the case if you changed `vim.o.selection`, or if you have a keymap that does something weird on selection.

**Comment by folke** [comment]
What does `:set sel?` say in the scratch buffer?

**Comment by ibutra** [comment]
I tried your new repro with that I can't reproduce the error.

`:set sel?` in the buffer says `selection=inclusive`
`:verb map V` returns `no mapping found`

**Comment by folke** [comment]
I just added an extra check to correct the visual selection boundaries.
Can you check with your normal config?

**Comment by ibutra** [comment]
It still selects one after the end of the line but now doesn't throw an error but works.

Thank you a lot!

**Comment by folke** [comment]
Are you on windows by any chance? Maybe visual line includes the last `\r` character or something like that?

**Comment by ibutra** [comment]
I am on windows, yes.
But with your repro I was also on windows today and couldn't reproduce it.

**Comment by folke** [comment]
Do you have key-model or select-mode set?

**Comment by ibutra** [comment]
Both are empty (default value)

**Comment by folke** [comment]
Weird. No idea how that's possible then.
Either way, my work-around seems to fix it

**Comment by ibutra** [comment]
Yes it does, thank you very much!

If I stumble upon the reason as to why this behaves this way I will let you know.

**Comment by shy-robin** [comment]
> Weird. No idea how that's possible then. Either way, my work-around seems to fix it

Thanks! It works after I update.
