### ISSUE TITLE
feature: notifier support custom backdrop

### ISSUE THREAD

**Issue by shy-robin** [folke/snacks.nvim#192]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I have read the `notifier` source, it's not possible to custom backdrop value.

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/b1480dd4-5295-4517-8bac-cb0578d671a8">

### Describe the solution you'd like

Support custom backdrop value for notifier.

### Describe alternatives you've considered

empty

**Comment by folke** [comment]
You can configure window styles.

opts.styles["notification.history"].backdrop = 100
