### ISSUE TITLE
bug(dashboard): Missing padding when last key was hidden

### ISSUE THREAD

**Issue by qw457812** [folke/snacks.nvim#194]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

macOS Sequoia 15.1.1 arm64

### Describe the bug

Thanks for your great plugins, when I hide key `q` in dashboard, the padding of keys section is also lost.

Part of opts:

```lua
keys = {
  ...
  { icon = " ", key = "q", desc = "Quit", action = ":qa", hidden = true },
},
```

Screenshot:

<img width="553" alt="image" src="https://github.com/user-attachments/assets/377eb53c-432e-4c65-9927-34abb3836ef7">[](url)

### Steps To Reproduce

1. Add `hidden = true` for `{ icon = " ", key = "q", desc = "Quit", action = ":qa" }`, which is last key in keys section.
2. Start nvim.

### Expected Behavior

Hide key `q` and keep the padding of keys section.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by qw457812** [comment]
Big fan here, you might find I even stole your wall.png.

**Comment by folke** [comment]
Fixed!

**Comment by qw457812** [comment]
Thank you!
