### ISSUE TITLE
bug: dashboard duplicate projects

### ISSUE THREAD

**Issue by sho-87** [folke/snacks.nvim#195]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Windows 11

### Describe the bug

Similar to #171, the projects list shows duplicate entries, but this seems more directly caused by capitalization:

![image](https://github.com/user-attachments/assets/97f5a7f1-5b33-448d-b97a-cecc8d05b022)

### Steps To Reproduce

Install lazyvim, open the same project multiple times

### Expected Behavior

Project entries should be unique if theyre on the same path on Windows

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      opts = {
        dashboard = {
          enabled = true,
          sections = {
            {
              pane = 2,
              title = "Projects",
              section = "projects",
            },
          },
        },
      },
    },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
won't fix. sorry
