### ISSUE TITLE
bug(statuscolumn): Duplicated extmarks signs when using virtual texts after the end of buffer

### ISSUE THREAD

**Issue by rachartier** [folke/snacks.nvim#198]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1272+g3d3a99e69c

### Operating system/version

WSL2 Ubuntu 22.04

### Describe the bug

Hi!

Hope you're all doing good.

An user opened an issue on my project https://github.com/rachartier/tiny-inline-diagnostic.nvim/issues/65#issuecomment-2513896242 
The thing is, with the default status column or ![statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim) all seems to works nicely, but with statuscolumn enabled in snacks, it repeat the last signs on all virtual lines after the last line on the buffer.

I can also reproduce this issue, as descriped in `repro` section.

Image from the user:
![391881443-f28f3028-d365-4738-93c0-1281ca109139](https://github.com/user-attachments/assets/d306eab1-006f-474a-b0e6-73849573eb20)

I was wondering if something can be done about it, to be iso compatible with default statuscolumn, or if I need to make an edge case for snack in the plugin.

### Steps To Reproduce

1. Have a lua lsp installed
2. Create a file "test.lua"
3. Enter in insert mode "     a a a a a a a a a a a a"
4. Place the cursor in normal mode on the first character

### Expected Behavior

Not having duplicated signs on virtual lines

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"folke/snacks.nvim",
			opts = {
				statuscolumn = {enabled = true},
			},
		},
		-- add any other plugins here
		{
			"neovim/nvim-lspconfig",
		},
		{
			"williamboman/mason.nvim",
			keys = {
				{ "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" },
			},
			lazy = false,
			opts = {},
		},
		{
			"williamboman/mason-lspconfig.nvim",
			opts = {
				ensure_installed = {
					"lua_ls",
				},
			},
		},
		{
			"nvim-treesitter/nvim-treesitter",
			opts = {
				ensure_installed = { "lua" },
			},
			config = function(_, opts)
				require("nvim-treesitter.configs").setup(opts)
			end,
		},
		{
			"rachartier/tiny-inline-diagnostic.nvim",
			event = "VeryLazy", -- Or `LspAttach`
			priority = 1000, -- needs to be loaded in first
			config = function()
				require("tiny-inline-diagnostic").setup()
			end,
		},
	},
})

vim.diagnostic.config({ virtual_text = false })
require("lspconfig").lua_ls.setup({})
```

**Comment by dpetka2001** [comment]
You mean the signs in the gutter? I can't reproduce this with the minimal repro. Also the minimal repro should look like this for completeness
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"folke/snacks.nvim",
			opts = {
				statuscolumn = {},
			},
		},
		-- add any other plugins here
		{
			"neovim/nvim-lspconfig",
		},
		{
			"williamboman/mason.nvim",
			keys = {
				{ "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" },
			},
			lazy = false,
			opts = {},
		},
		{
			"williamboman/mason-lspconfig.nvim",
			opts = {
				ensure_installed = {
					"lua_ls",
				},
			},
		},
		{
			"nvim-treesitter/nvim-treesitter",
			opts = {
				ensure_installed = { "lua" },
			},
			config = function(_, opts)
				require("nvim-treesitter.configs").setup(opts)
			end,
		},
		{
			"rachartier/tiny-inline-diagnostic.nvim",
			event = "VeryLazy", -- Or `LspAttach`
			priority = 1000, -- needs to be loaded in first
			config = function()
				require("tiny-inline-diagnostic").setup()
			end,
		},
	},
})

vim.diagnostic.config({ virtual_text = false })
require("lspconfig").lua_ls.setup({})
```
Here is a screenshot with above minimal repro 
![2024-12-04_14-17](https://github.com/user-attachments/assets/d723a30a-8235-49a4-b4dc-e1cde48de4a7)

**Comment by rachartier** [comment]
Oh yes sorry, thank you.

You need to add statuscolumn = { enabled = true} in snacks.nvim

I will edit my issue

**Comment by rachartier** [comment]
The fact is, even when added, no status column is displayed...

**Comment by rachartier** [comment]
You're right, for now I cannot pinpoint where this issue is coming from.

**Comment by dpetka2001** [comment]
So, you're not able to reproduce the problem like me? Then I believe this is not a `snacks.statuscolumn`, because this repro is just the bare minimum. Could as well be a user configuration issue. I don't know what the user did in the issue in your repo, but you could suggest him to strip down his configuration and try to find the culprit. He might have another plugin that tries to overwrite the statuscolumn set by Snacks and that causes some kind of conflict (just a guess from my part).

**Comment by dpetka2001** [comment]
I also tried in a default LazyVim installation (which uses `snacks.statuscolumn`), which I also use for my personal configuration and got same results. Screencast following

[Screencast_2024-12-04-15-48-59.webm](https://github.com/user-attachments/assets/3fd6be36-8cf9-47e5-ba33-e57b315d618d)

**Comment by rachartier** [comment]
With my config I can reproduce the issue:
![image](https://github.com/user-attachments/assets/e8b88c58-3dd3-4eda-ba36-a64bbe2fe92e)

Can you try adding a blank line ? It can takes some attemps by switching back and forth between line 1 and 2

**Comment by rachartier** [comment]
Seems fixed with your last update, well done!

The only issue now is the sign sometimes jitters (seems okay in default and statuscol.nvim):
![debug_snacks](https://github.com/user-attachments/assets/c2a116c0-2ce8-4840-81ac-90611d630d8b)
