### ISSUE TITLE
bug: `enabled` field doesn't seem to take effect.

### ISSUE THREAD

**Issue by amedoeyes** [folke/snacks.nvim#2]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Linux 6.11.6.arch1-1

### Describe the bug

Setting the `enabled` field to `false` doesn't seem to do anything. Here I'm trying to disable `notifier` and `statuscolumn` but they still function.
 
![image](https://github.com/user-attachments/assets/0c563dcc-1db8-46c4-a821-904ccf1ab069)

When I print `Snacks.config`:

![image](https://github.com/user-attachments/assets/6d5faf14-5cf6-4558-b3aa-e5377a42d860)

### Steps To Reproduce

1. Set the `enabled` field of `notifier` to `false`
2. Display a notification with `vim.notify`
3. `notifier` will display the notification

### Expected Behavior

Disabled features should be disabled.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"folke/snacks.nvim",
			opts = {
				statuscolumn = { enabled = false },
				notifier = { enabled = false },
			},
		},
	},
})

for i = 1, 10 do
	vim.defer_fn(function()
		vim.notify("Hello " .. i, "info", { id = "test" })
	end, i * 500)
end
```

**Comment by iguanacucumber** [comment]
this should be reopened as i'm still having this issue

**Comment by roguesherlock** [comment]
yeah I am also facing similar issue even with the latest release

**Comment by folke** [comment]
You probably wanted to disable notifier?
The problem was that noice would still use snacks, even when disabled.
Just fixed that in both snacks (and lazyvim if you use that)

**Comment by roguesherlock** [comment]
yes. Thank you so much @folke! Love all your plugins!
