### ISSUE TITLE
feature: Notification displaying the number of changes when renaming files.

### ISSUE THREAD

**Issue by bassamsdata** [folke/snacks.nvim#202]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

[Rename Module]
Not knowing how many changes happened when renaming a file.

### Describe the solution you'd like

Thank you for these QoL modules! This might be a small detail, but I’d recommend adding a notification that displays something like "4 changes applied across 4 files." It would be especially helpful for tracking updates when renaming a file. I have it in my lsp rename like this:
<img width="731" alt="Screenshot 2024-12-04 at 11 19 05 AM" src="https://github.com/user-attachments/assets/14fdcf74-59fa-4dfa-ad37-c0210de7cecb">

Thank you

### Describe alternatives you've considered

not an issue per se, so no.

**Comment by folke** [comment]
There's no way to know how many changes were done.
All I know is that the file was renamed.

**Comment by bassamsdata** [comment]
ah good to know, thanks.
