### ISSUE TITLE
bug: backdrop always remain the same

### ISSUE THREAD

**Issue by jaymorelli96** [folke/snacks.nvim#205]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

I have tried multiple times to change the highlight group for `SnacksBackdrop` but it always stay the same dark one. I want to disable the backdrop, or at least be able to change the color. 

I tried `vim.api.nvim_set_hl(0, 'SnacksBackdrop', { bg = '#e5e9f0' })` or any other color, also with 'none' and no success always the same. When I search the highlight with telescope, it shoes me that the `SnacksBackdrop` has the right color but it also show me a `SnacksBackdrop_000000` highlight that I cannot change the color. Also after I try to use the backdrop, lets say using lazygit, the highlight for `SnacksBackdrop` goes back to black

### Steps To Reproduce

1. Change the highlight of `SnacksBackdrop` by setting `vim.api.nvim_set_hl(0, 'SnacksBackdrop', { bg = '#e5e9f0' })`

### Expected Behavior

Expected to be a different color, but still the same black

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

vim.api.nvim_set_hl(0, "SnacksBackdrop", { bg = "#e5e9f0" })

require("lazy.minit").repro({
	spec = {
		{ "folke/snacks.nvim", opts = {}, lazygit = { enabled = true } },
	},
})
```

**Comment by folke** [comment]
You disable the backdrop by changing the backdrop settings. It's in the `win` docs.
Also, please ask a question in discussions instead. This is for issues.

**Comment by dpetka2001** [comment]
Following should work
```lua
{
  "folke/snacks.nvim",
  opts = {
    win = {
      backdrop = {
        bg = "#e5e9f0", -- backdrop background color
        blend = 70, -- backdrop transparency (0-100)
      },
    },
  },
}
```

**Comment by folke** [comment]
Or set `backdrop = false` if you don't want a backdrop
