### ISSUE TITLE
bug: cannot use snacks's function by setting setcellwidths

### ISSUE THREAD

**Issue by nekowasabi** [folke/snacks.nvim#209]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS 14.6.1

### Describe the bug

When you use setcellwidths() to change the cell width of a multi-byte font, an error related to character width will occur.

```
E5108: Error executing lua ...er/.repro/data/nvim/lazy/snacks.nvim/lua/snacks/util.lua:43: E1512: Wrong character width for field "extends"
stack traceback:
        [C]: in function 'nvim_set_option_value'
        ...er/.repro/data/nvim/lazy/snacks.nvim/lua/snacks/util.lua:43: in function 'wo'
        ...her/.repro/data/nvim/lazy/snacks.nvim/lua/snacks/win.lua:399: in function 'show'
        ...her/.repro/data/nvim/lazy/snacks.nvim/lua/snacks/win.lua:204: in function 'win'
        ...repro/data/nvim/lazy/snacks.nvim/lua/snacks/terminal.lua:89: in function 'open'
        ...repro/data/nvim/lazy/snacks.nvim/lua/snacks/terminal.lua:135: in function 'get'
        ...repro/data/nvim/lazy/snacks.nvim/lua/snacks/terminal.lua:146: in function 'lazygit'
        [string ":lua"]:1: in main chunk

```

### Steps To Reproduce

1. move to using github repository ex. `cd /path/to/project`
2. boot nvim
3. execute `lua Snacks.lazygit()`

### Expected Behavior

Enable to use `lua Snacks.lazygit()` command.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- using multibyte language(ex. Japanese, Chinese etc...) font
vim.fn.setcellwidths({
  { 0x2100, 0x214d, 2 },
  { 0x26A0, 0x26A0, 2 },
  { 0x2014, 0x2014, 2 },
  { 0x2026, 0x2026, 2 },
  { 0x2192, 0x2192, 2 },
  { 0x203B, 0x203B, 2 },
  { 0x2935, 0x2935, 2 },
  { 0x2459, 0x2469, 2 },
  { 0x2606, 0x2606, 2 },
})

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
      lazygit = { enable = true },
    } },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
This is not an issue with snacks.
You are configuring the elipsis character to be double with and apparently that's not allowed in Neovim.

```lua
    listchars = "extends:…,tab:  ",
```

**Comment by nekowasabi** [comment]
@folke 
Thank you for confirming!
After deleting U+2026, it worked as expected.
