### ISSUE TITLE
feature: Make notifier response compatible with nvim-notify

### ISSUE THREAD

**Issue by kristijanhusak** [folke/snacks.nvim#21]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Some of the plugins embraced `nvim-notify` as a standard and implemented their notifications around it. In my case, that's https://github.com/dmmulroy/tsc.nvim. It provides progress through `vim.notify`, and expects `vim.notify` to return a table with an id (`{ id = id }`).
Notifier snack returns the id number directly, which makes it incompatible and breaks this plugin. Also, `nvim-notify` allows updating existing notification via `replace` property on opts instead of `id`.

### Describe the solution you'd like

I'd like for notifier to be compatible with `nvim-notify` so it can be swapped out with other plugins. This includes returning a different structure and handling some of the additional options.

### Describe alternatives you've considered

I'm currently monkey patching `vim.notify` manually and handling these cases.
```lua
    vim.notify = function(msg, level, o)
      o = o or {}
      if o.replace then
        o.id = o.replace
      end
      local result = Snacks.notifier.notify(msg, level, o)
      if type(result) == 'table' then
        return result
      end
      return { id = result }
    end
```

I'm fine with doing it manually, but it might be useful to document this in case someone else runs into a similar issue.

**Comment by folke** [comment]
Sorry, but they should just update their plugin.
Replacing notifications is **much** easier with snacks.

You don't even need to keep track of the notification ids for tsc.

They can just always pass `id = "tsc"`.

Snacks will then update the existing notification or create a new one if it doesn't exist.

Again, no need to keep track of the ids...
