### ISSUE TITLE
bug: Terminal statusline flashing when typing

### ISSUE THREAD

**Issue by dotfrag** [folke/snacks.nvim#22]
I was meaning to open in this in LazyVim, sorry. Please close.

https://github.com/LazyVim/LazyVim/issues/4724

**Comment by folke** [comment]
@dpetka2001 this is a repro:

```lua
vim.cmd("botright 20 split")
vim.cmd.terminal()
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-n>")
vim.opt_local.winbar = "title: %{b:term_title}" -- this causes the flickering
vim.cmd.startinsert()
```
Would be great if someone could report to lualine...

**Comment by folke** [comment]
Opened https://github.com/nvim-lualine/lualine.nvim/issues/1323

**Comment by dpetka2001** [comment]
On an unrelated note could you help how to open the terminal in `float` position by default? I tried
```lua
opts = {
        terminal = {
          win = {
            position = "float",
          },
        },
}
```
but it's not working. But maybe I'm doing something wrong.

**Comment by folke** [comment]
That was a bug. Just fixed it :)

**Comment by folke** [comment]
not yet

**Comment by folke** [comment]
nw it should be good

**Comment by dpetka2001** [comment]
Thank you!!
