### ISSUE TITLE
bug: Failed to run config for snacks.nvim

### ISSUE THREAD

**Issue by pkropachev** [folke/snacks.nvim#227]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1328+g4889935a7a

### Operating system/version

Ubuntu 20.04

### Describe the bug

I get the following notification immediatly after run the nvim.

![image](https://github.com/user-attachments/assets/77dcb053-9f30-4126-9d2d-b1cf3850c67a)

![image](https://github.com/user-attachments/assets/89086ca4-9304-4bd0-9ce0-72b84c430512)

### Steps To Reproduce

1. Run `nvim` with latest version of snacks.nvim.

### Expected Behavior

No any errors.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by pkropachev** [comment]
The same behaviour with nvim `v0.10.2`.

**Comment by zivkovicn** [comment]
+ 1 on `v0.10.2`

**Comment by echaya** [comment]
+1 on windows with v0.10.2

**Comment by fang2hou** [comment]
https://github.com/folke/snacks.nvim/commit/614df63acfb5ce9b1ac174ea4f09e545a086af4d#commitcomment-150152958

**Comment by patelharsh9797** [comment]
After updating the recent snacks version I started getting that issue as well.
