### ISSUE TITLE
bug(indent): draw indent with `shiftwidth` maybe not correct in some cases

### ISSUE THREAD

**Issue by fang2hou** [folke/snacks.nvim#233]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macOS 15.1.1 (24B2091)

### Describe the bug

I changed my indent drawing plugin from `mini.indentscope` (LazyVim Extra) to snacks.nvim indent.
However I noticed that snacks.nvim indent bugged in some files with tabs.
I checked the code, and I am sure that in snacks ctx, the shiftwidth is 2.

The issue can be 100% reproduced with the following minimum `repro.lua`.

![image](https://github.com/user-attachments/assets/3c4bfd9b-1245-4804-8962-65da2d84c57b)

### Steps To Reproduce

1. Use the following stylua.toml to format lua files.
   ```toml
   [sort_requires]
   enabled = true
   ```
2. Use lazyvim default settings or use following vim setting.
   ```vim
   set tabstop=2
   set shiftwidth=2
   ```
4. Open the formatted file, the indent looks not correct.

### Expected Behavior

The indent should be rendered in correct space, current the middle of the tab is also rendered

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Settings from LazyVim defaults
vim.cmd([[
    set tabstop=2
    set shiftwidth=2
]])

require("lazy.minit").repro({
	spec = {
		{ "folke/snacks.nvim", opts = { indent = { scope = { underline = true } } } },
	},
})
```

**Comment by folke** [comment]
I don't seem to be able to reproduce this.
That repro file shows exactly how it should for me.
Your screenshot also shows 4 characters for each indent? With shiftwidth=2, there would indeed render 2 indents per real indent.

**Comment by folke** [comment]
Are you sure your stylua settings are correct? And correspond with shiftwidth and tabstop in Neovim?

**Comment by fang2hou** [comment]
@folke 
I am sorry for the confusion in my `ftplugin` setup. And I also mistakenly assumed that the issue was with tab rendering, rather than recognizing the problem with the `vim.cmd` settings when verifying the reproduction code.

The correct reproduction setting is as follows:
```lua
vim.cmd([[
    set tabstop=4
    set shiftwidth=2
]])
```

I didn’t realize this config miss because `mini.indentscope` handled tabs correctly, even when `tabstop` and `shiftwidth` were not the same.

**Comment by fang2hou** [comment]
I added `NMAC427/guess-indent.nvim` to auto guess the indent and set the tabstop and shiftwidth, snacks indent works great now with multiple formatters and languages.

**Comment by folke** [comment]
Even with tabstop=4 and shiftwidth=2, I think the way snacks renders indent guides is still correct.

**Comment by fang2hou** [comment]
@folke 
Good morning from Japan. Here is the video to show the reproduction.
https://github.com/user-attachments/assets/d079cfc1-c247-4ef0-9340-3122bdd18a6a
