### ISSUE TITLE
feature(indent): allow scope underline to match scope highlight group

### ISSUE THREAD

**Issue by dstanberry** [folke/snacks.nvim#234]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Currently if `config.scope.underline` is enabled, the hl_group is hardcoded to `SnacksIndentScopeUnderLine`.

### Describe the solution you'd like

It would be nice if `config.scope.underline` could be extended to accept a boolean, string, or list of strings.
This would allow for the underline to match the scope when a list is used.

### Describe alternatives you've considered

n/a

**Comment by dstanberry** [comment]
4e96e692e8a3c6c67f9c9b2971b6fa263461054b introduced a visual bug:
https://github.com/folke/snacks.nvim/blob/4e96e692e8a3c6c67f9c9b2971b6fa263461054b/lua/snacks/indent.lua#L241

should instead be
```lua
    vim.api.nvim_buf_set_extmark(scope.buf, ns, scope.from - 1, col, {
```
or the max of `col` and `0`..?

**Comment by folke** [comment]
Can you update the code? That's an old line.
If the problem persists, can you show a screenshot of what is wrong?

**Comment by dstanberry** [comment]
https://github.com/folke/snacks.nvim/blob/b5cb90f91dedaa692c4da1dfa216d13e58ad219d/lua/snacks/indent.lua#L264
![Screenshot 2024-12-10 130500](https://github.com/user-attachments/assets/7be5a4ee-d42d-45da-ae1c-e40be7839f07)

**Comment by folke** [comment]
For me it showed correctly. So probably NEovim version.
I just pushed a change to do it differerntly. Can you check if that works?

**Comment by Isrothy** [comment]
It works for me now.

**Comment by dstanberry** [comment]
Works now, ty!
