### ISSUE TITLE
feature: Add text objects to indent module

### ISSUE THREAD

**Issue by Isrothy** [folke/snacks.nvim#238]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Extend the existing indent module with text objects to complement the visual selection functionality, providing a consistent user experience for indentation-based operations.

### Describe the solution you'd like

Similar to https://github.com/kiyoon/treesitter-indent-object.nvim or https://github.com/echasnovski/mini.indentscope
```lua
opts = {
  indent = {
    enabled = true,
    text_objects = {
      inside = "ii",  -- select inside indentation level
      around = "ai"   -- select around indentation level
    }
  }
}
```

The implementation should reuse the existing indentation detection logic from the visual module to ensure consistent behavior between visual selections and text objects.

### Describe alternatives you've considered

no

**Comment by folke** [comment]
dup of #231
