### ISSUE TITLE
feature: notifier for cmdline

### ISSUE THREAD

**Issue by OneOfOne** [folke/snacks.nvim#24]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Cmdline opens under the status line, unlike with noice.

### Describe the solution you'd like

Add a notifier box for it like noice.

### Describe alternatives you've considered

Sticking to noice.

**Comment by folke** [comment]
Do you mean something like noice's mini view?

You can achieve the same with `top_down = false` and `style = "minimal"`.

**Comment by OneOfOne** [comment]
@folke that was it, thank you.
