### ISSUE TITLE
bug(indent):  char doesnt render when an empty line is inserted on the first line of a scope

### ISSUE THREAD

**Issue by quebn** [folke/snacks.nvim#246]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

archlinux

### Describe the bug

indent character doesnt render when inserting an empty newline below a scope.

Image before inserting an empty newline.
![image](https://github.com/user-attachments/assets/07c4cf9d-5c95-4d57-8d91-b12930b86e1e)

Image after inserting an empty newline.
![image](https://github.com/user-attachments/assets/9741a207-78c9-4254-b8d2-a60398490665)

### Steps To Reproduce

1. use the repro code.
2. create a table with values.
3. insert an empty new line on the on the first line of the table. 

### Expected Behavior

indent character should render.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { indent = {}}},
  },
})
```

**Comment by folke** [comment]
@quebn can you check the update? I made some slight changes to better deal with blank lines

**Comment by quebn** [comment]
@folke looks good now, thanks.
![image](https://github.com/user-attachments/assets/c250c7a5-89cc-4c72-a6ab-1bb857742bc3)
