### ISSUE TITLE
bug: (scroll) will re-scroll from begining position when 'flash.nvim' finds a match 

### ISSUE THREAD

**Issue by RomaLzhih** [folke/snacks.nvim#248]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.3

### Operating system/version

wsl

### Describe the bug

As the title says, when we search something by "/" and find a match, then press `<CR>`, the Scroll will go back to the position we started the search and then scroll to the match position, which is wired. 

### Steps To Reproduce

I believe installing the flash.nvim, then using its override of "/" and searching a word outside of the screen scope will reproduce the problem. 

### Expected Behavior

There is no such scroll. When it matches, it stops. 

### Repro

```lua
https://github.com/RomaLzhih/neovim_config
```

**Comment by folke** [comment]
Just pushed a bunch of changes for scroll and it probably also fixed this issue.
At least I can't reproduce it with the latest changes.
Do let me know if you'd still encounter issues

**Comment by RomaLzhih** [comment]
Thanks for your help. I am wondering whether it is possible to disable scrolling in terminal buffers. When I run a command that produces output with multiple lines, the scroll throws error messages and then gets stuck. Thanks!

**Comment by RomaLzhih** [comment]
```{lua}
{
  animate = {
    duration = { step = 15, total = 250 },
    easing = "linear",
  },
  filter = function(buf)
    -- Exclude terminal buffers
    return vim.g.snacks_scroll ~= false 
           and vim.b[buf].snacks_scroll ~= false 
           and vim.bo[buf].buftype ~= 'terminal'
  end,
}
```

**Comment by folke** [comment]
I just pushed a change to disable in terminals by default.

**Comment by RomaLzhih** [comment]
Great! Also, the `prompt` may need to be disabled either, e.g., we are searching among many files in the telescope.nvim for fzf.lua
