### ISSUE TITLE
bug: Snacks.toggle.zen() doesn't work

### ISSUE THREAD

**Issue by igorgue** [folke/snacks.nvim#259]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev

### Operating system/version

Linux  6.11.7 NIXOS 24.11

### Describe the bug

```
Snacks.toggle.zen()
```

Doesn't do anything to me, and when I do `Snacks.zen()` it does but then I cannot close zen mode with `Snacks.toggle.zen()` nor with `Snacks.zen()`.

### Steps To Reproduce

1. Run `Snacks.toggle.zen()`
2. Nothing happens

### Expected Behavior

It was working before without the toggle... repro.lua shows the error as well.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by igorgue** [comment]
Here's some log:
```
Error executing vim.schedule lua callback: ...or/.local/share/nvim/lazy/snacks.nvim/lua/snacks/dim.lua:114: attempt to index a nil value
stack traceback:
	...or/.local/share/nvim/lazy/snacks.nvim/lua/snacks/dim.lua:114: in function 'cb'
	.../share/nvim/lazy/snacks.nvim/lua/snacks/animate/init.lua:86: in function 'update'
	.../share/nvim/lazy/snacks.nvim/lua/snacks/animate/init.lua:173: in function <.../share/nvim/lazy/snacks.nvim/lua/snacks/animate/init.lua:170>
```

I also tried on neovim `0.10`, same result.

**Comment by igorgue** [comment]
On `0.10` actually, `Snacks.toggle.zen()` does start zen mode, but running it again doesn't re-open it.

**Comment by folke** [comment]
Also, `Snacks.toggle.zen()` returns a toggle object with a `map` function.
You can also use it to toggle directly (which makes little sense), but then you should do `Snacks.toggle.zen():toggle()`

**Comment by folke** [comment]
`Snacks.toggle.zen():map("<leader>uz")`
That will create the mapping with correct description and will show as a toggle with the correct state in which-key.
Like here:

![image](https://github.com/user-attachments/assets/7d79a2a4-0972-496f-9ad9-abaa97b309e1)

**Comment by igorgue** [comment]
@folke now I got the toggle state of the icon changes, that's so cool, thank you so much!
