### ISSUE TITLE
bug: transparency issues with notifier

### ISSUE THREAD

**Issue by scottmckendry** [folke/snacks.nvim#26]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

NixOS 24.11 (Linux 6.6.59)

### Describe the bug

Currently in the process of adding support for snacks.nvim to a colorsheme and I'm noticing some unexpected behaviour with transparency. 

I've used tokyonight's implementation as an example, where the `bg` property of each group should be set to `"NONE"`.

Unfortunately, transparency is not being applied:
![image](https://github.com/user-attachments/assets/25215384-981b-4a9c-b317-98e141db2363)

I can set specific colours in `bg` and they work as expected, e.g. this wonderful pink colour 😉 :

![image](https://github.com/user-attachments/assets/98c790c8-128a-4410-8601-d7c02ed3fd18)

FYI - I also get the same transparency problem with tokyonight.nvim.

### Steps To Reproduce

1. Using a colorsheme that supports transparency, set the `bg` properties of the `SnacksNotifier...` groups to `"NONE"`
2. run `:lua vim.notify("Hello!")`

### Expected Behavior

Background if the notification should be transparent.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        { "folke/snacks.nvim", lazy = false, priority = 1000 },
        {
            "folke/noice.nvim",
            lazy = false,
            config = function()
                require("noice").setup({})
            end,
        },
        -- add any other plugins here
        {
            "folke/tokyonight.nvim",
            lazy = false,
            priority = 1000,
            config = function()
                require("tokyonight").setup({
                    transparent = true,
                })
                vim.cmd("colorscheme tokyonight")
            end,
        },
    },
})
```

**Comment by tris203** [comment]
I was just reporting this, I am getting the same issue with tokyonight theme with transparency set

![image](https://github.com/user-attachments/assets/00291217-adfc-46be-811a-bca7d9b2c7c9)
