### ISSUE TITLE
feature: add `esc_esc` & `ctrl_hjlk` like before

### ISSUE THREAD

**Issue by konosubakonoakua** [folke/snacks.nvim#262]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

With ctrl_hjlk enabled in snacks_termnial, I cannot use them in bash.

### Describe the solution you'd like

add a switch like before: `esc_esc = false, ctrl_hjkl = false, border = "rounded",`

### Describe alternatives you've considered

disable snacks_terminal

**Comment by folke** [comment]
`esc` should not cause issues because of the way that's implemented.
You can disable the nav keys (that's a LazyVim thing), with `opts.terminal.win.nav_h = false` etc for the `snacks.nvim` plugin,
