### ISSUE TITLE
feature: bufdelete - hidden buffers

### ISSUE THREAD

**Issue by mosheavni** [folke/snacks.nvim#266]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I want to switch from a different bufdelete plugin which has `:BDelete hidden` which deletes the hidden buffers

### Describe the solution you'd like

`Snacks.bufdelete.hidden()`

### Describe alternatives you've considered

not switching to snacks' bufdelete

**Comment by folke** [comment]
```lua
Snacks.bufdelete({
  filter = function(buf)
    return vim.bo[buf].bufhidden
  end
})
```

**Comment by mosheavni** [comment]
```lua
        local non_hidden_buffers = {}
        for _, win in ipairs(vim.api.nvim_list_wins()) do
          table.insert(non_hidden_buffers, vim.api.nvim_win_get_buf(win))
        end
        Snacks.bufdelete.delete(function(buf)
          return not vim.tbl_contains(non_hidden_buffers, buf)
        end)

```

**Comment by folke** [comment]
```lua
Snacks.bufdelete({ filter = function(buf) 
  return #vim.fn.win_findbuf(buf) == 0
end })
```
