### ISSUE TITLE
feature: Improved vim.ui.select?

### ISSUE THREAD

**Issue by jdrupal-dev** [folke/snacks.nvim#267]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Do you plan on adding a "select" module similar to the input module for enhancing the UI of vim.input.select?

### Describe the solution you'd like

Would be nice to have something similar to "input" for vim.ui.select.

### Describe alternatives you've considered

Currently I use dressing.nvim, but would like to replace it with snacks.input and hopefully snacks.select :)

**Comment by jdrupal-dev** [comment]
I just saw that fzf-lua has an easy way to do this:
```lua
require("fzf-lua").register_ui_select()
```

Please close this issue if it's out of scope for this project.

**Comment by folke** [comment]
that's what I use as well
