### ISSUE TITLE
bug: (indent) `only_scope = true` causes rendering bug

### ISSUE THREAD

**Issue by rawhat** [folke/snacks.nvim#268]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1341+g5eda7aafe9

### Operating system/version

MacOS 15.1.1

### Describe the bug

When enabling `only_scope`, I get this strange rendering where it seems to shift the non-present, further indented bits over top of the content in the scope.  Upon navigating to certain levels, it seems to go away.

https://github.com/user-attachments/assets/fd8485b3-640b-46ea-a70e-af968fb5800e

### Steps To Reproduce

Enable `indent = { only_scope = true }`, move between scopes.

### Expected Behavior

It should not affect any text and highlight the current scope.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
       	indent = { enabled = true, indent = { only_scope = true } },
    } },
    -- add any other plugins here
  },
})
```

**Comment by rawhat** [comment]
I was also seeing the statusline duplicated, so that's a strange one 😅 

Unfortunately, I'm still seeing the same issue with `snacks` updated.

![image](https://github.com/user-attachments/assets/584ed253-0fd9-4fe8-a47d-e0965d0f021f)

It seems like it moves the indent lines into the scope.  Like the above scope's line is "moved" to where the current scope one is, with the highlight, and then the prior indent lines get shifted forward with an additional indentation level:

![image](https://github.com/user-attachments/assets/8394ab0d-b740-4138-a1da-d9b1dcc912ac)

Probably describing it poorly, but hopefully that's helpful information 😬

**Comment by folke** [comment]
What Neovim version are you on? Pretty sure these are rendering bugs in Neovim.

**Comment by rawhat** [comment]
I am on the latest nightly as of this morning.  I also just tried on `v0.10.2` and still saw the same behavior 🤔 but I can try other versions if needed.

**Comment by folke** [comment]
Found the issue, but have to go here. I'm basically setting extmarks at negative offsets.
Will fix later tonight or tomorrow.

**Comment by rawhat** [comment]
You're the best.  Thank you!  No rush 😄

**Comment by folke** [comment]
Should be fixed now. Can you check if your type of rendering issues are also fixed?

**Comment by rawhat** [comment]
It looks great, thank you!
