### ISSUE TITLE
bug: undercurls from buffer below (via TreeSitter), appear inside notifier notifications

### ISSUE THREAD

**Issue by benfrain** [folke/snacks.nvim#271]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

MacOS 15.1.1

### Describe the bug

Using Kitty 0.37

Viewing a markdown file with urls which has undercurls. When a notification fires, the undercurls 'show through' in to the notification. Disabling TreeSitter makes the problem go away

### Steps To Reproduce

Open a markdown file with a url in, that shows undercurls (TreeSitter must be enabled), beneath where the notification will appear
Fire a notification with `:lua Snacks.notify.notify("Hello")`
Observe undercurls showing through the notification

### Expected Behavior

Notification displays without underlines from buffer below showing through

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
notifier = {enabled = true},
    }, },
    -- add any other plugins here
 {
   "nvim-treesitter/nvim-treesitter",
   build = ":TSUpdate",
   config = function () 
      local configs = require("nvim-treesitter.configs")

      configs.setup({
          ensure_installed = {  "markdown" },
          sync_install = false,
          highlight = { enable = true },
          indent = { enable = true },  
        })
    end
 }
  },
})
```

**Comment by folke** [comment]
That's how it should be. The notifier window has a default winblend applied.

Change it with `snacks.nvim: opts.styles.notification.wo.winblend = 0`
