### ISSUE TITLE
bug: LuaLS 3.13.3 breaks @class inheritance optional @fields annotations hack

### ISSUE THREAD

**Issue by minusfive** [folke/snacks.nvim#274]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 14.6.1

### Describe the bug

As of [LuaLS v3.13.3](https://github.com/LuaLS/lua-language-server/releases/tag/3.13.3) the `@class` inheritance hack to mark all `@field`s as optional [no longer works](https://github.com/LuaLS/lua-language-server/pull/2970). As a consequence all config fields appear mandatory now, and a wall of warnings is shown.

This typing hack seems to be pervasive across the Lua ecosystem, so not sure what next steps should be. In the meantime it seems the only solution is to explicitly declare all `@field`s as optional (`?`).

Submitting this bug primarily as a way to track this issue. Will try and submit a PR when I have a chance.

![Screenshot 2024-12-13 at 00 43 52](https://github.com/user-attachments/assets/a8dcb0b4-047d-4da0-b8d2-2f3545dfed9b)

### Steps To Reproduce

1. Update LuaLS
2. Peruse configs and behold the wall of "missing fields" warnings

### Expected Behavior

All config fields should be explicitly marked as optional.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      opts = {
        ---@type snacks.dashboard.Config
        dashboard = {}
      }
    },
  },
})
```

**Comment by folke** [comment]
I'm not going to duplicate all configs in an optional type.
You'll have to wait till luals implements `---class (partial) foo: config`, or provide a PR to luals for exactly this.

**Comment by tomlau10** [comment]
Hi, I come from https://github.com/LuaLS/lua-language-server/pull/2970 and I just implemented the `---@class (partial) foo: config` syntax in https://github.com/LuaLS/lua-language-server/pull/3024, which in short brings back the original checking behavior for a class containing `partial` attribute.

Maybe you guys would like to keep an eye on it 👀 @minusfive @folke
