### ISSUE TITLE
bug(lazygit): pressing Escape quickly twice puts it in normal mode.

### ISSUE THREAD

**Issue by quebn** [folke/snacks.nvim#280]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

archlinux

### Describe the bug

minor bug though as user can just avoid pressing Esc twice quickly and pressing `i` or `a` after this brings it back.  also tried this on kdheepak/lazygit.nvim and this bug doesnt happen. 

### Steps To Reproduce

1. Open Snacks.lazygit
2. Press Esc quickly twice

### Expected Behavior

shouldn't go into normal mode

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { lazygit = { enabled = true}} },
  },
})
```

**Comment by folke** [comment]
That's not a bug. That's on purpose. Check the docs to disable the keymap in the style if you don't want that.

**Comment by quebn** [comment]
> Aware that this issue has been closed for a bit, but did you manage to change this behavior [@quebn](https://github.com/quebn) ?
you have to change the default keymap of the [snacks.terminal](https://github.com/folke/snacks.nvim/blob/main/docs/terminal.md)
here is how i do it. but do note tho that you have to use the old way `ctrl+\ ctrl+n` exit to normal if you use the neovim terminal.
```lua    
terminal   = {
      win = {
        keys = {
          term_normal = false,
        },
      },
    },
```

**Comment by paolomissagia** [comment]
Ah, you're a star, @quebn . I was looking into win keymaps for some reason.

**Comment by tartansandal** [comment]
Got this working with 
```lua
  {
    "snacks.nvim",
    opts = {
      lazygit = { enabled = true },
      styles = {
        lazygit = { keys = { term_normal = false } },
      },
    },
  }
```
Perhaps this could be documented under lazygit?  Going to normal mode is very counter intuitive here.

**Comment by mhyun-dpi** [comment]
I also found this counter intuitive. These keys are mentioned the `terminal` style, but the `lazygit` style is just a blank table. It's not immediately obvious the terminal keys would be inherited.
