### ISSUE TITLE
feature(indent): option to show the indent at the cursor

### ISSUE THREAD

**Issue by gibfahn** [folke/snacks.nvim#282]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

The default behaviour of https://github.com/echasnovski/mini.indentscope is this option:

```lua
    -- Whether to use cursor column when computing reference indent.
    -- Useful to see incremental scopes with horizontal cursor movements.
    indent_at_cursor = true,
```

this allows you to easily see larger scopes than the one you are currently on just by moving the cursor to the left

| Inner scope | Outer scope |
| - | - |
| ![](https://github.com/user-attachments/assets/e5b74e8d-0b2a-4881-ab0b-9245a7aa7cd1) | ![](https://github.com/user-attachments/assets/a6e88057-4fda-4ccc-bb01-b969f51dc9d0) |

### Describe the solution you'd like

I'd like to have this option available in snacks.indent . Don't mind whether it's the default as long as I can configure it.

### Describe alternatives you've considered

Keep using mini.indentscope 😁 

But I prefer using the defaults in LazyVim where possible.

**Comment by GiovanePS** [comment]
Yes! Mini.identscope is completely perfect! Folke could copy it entirely hahaha

And there are other issues in snacks.indent, like switch case in golang never be indented:
![image](https://github.com/user-attachments/assets/4a1578c0-d7df-4ada-8b1b-1f84f094d88b)

While this changes don't come, how do you are using the identscope? In my config, i disabled snacks.indent, but the indentscope is like this:
![image](https://github.com/user-attachments/assets/a2abc382-2418-4d59-87d2-e73583d2fed0)

Only works properly when i use the ident-blankline extra plugin too, but was not like that before update:
![image](https://github.com/user-attachments/assets/3928b97d-8f9b-48b4-b307-5c0b3545d298)

**Comment by folke** [comment]
This has now been added. It defaults to `true`.
Works for both treesitter and indent based scopes.

For text objects and jumps, the setting defaults to `false`.

**Comment by gibfahn** [comment]
Works great, thanks!
