### ISSUE TITLE
feature: header graphics

### ISSUE THREAD

**Issue by resistorsoftware** [folke/snacks.nvim#283]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I added header = [[ "foo"]] to my header sections but it only ever renders the default Neovim text.

### Describe the solution you'd like

I was wondering if we could use any old art like the alpha.lua plugin uses.

### Describe alternatives you've considered

Have not considered anything. just curious as to how one might override the default.

### Additional context

 [[                                                                       ]],
      [[                                                                     ]],
      [[       ████ ██████           █████      ██                     ]],
      [[      ███████████             █████                             ]],
      [[      █████████ ███████████████████ ███   ███████████   ]],
      [[     █████████  ███    █████████████ █████ ██████████████   ]],
      [[    █████████ ██████████ █████████ █████ █████ ████ █████   ]],
      [[  ███████████ ███    ███ █████████ █████ █████ ████ █████  ]],
      [[ ██████  █████████████████████ ████ █████ █████ ████ ██████ ]],
      [[                                                                       ]],

**Comment by folke** [comment]
Yes of course you can. Please check the docs or ask in discussions.

**Comment by Jay-Madden** [comment]
https://github.com/folke/snacks.nvim/discussions/341 i found an answer to this question in this discussion post
