### ISSUE TITLE
bug(indent): Incorrect indent guides for continuation indents

### ISSUE THREAD

**Issue by andreihh** [folke/snacks.nvim#286]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Ubuntu 22.04.5 LTS x86_64

### Describe the bug

The `indent` module displays multiple indent guides when the continuation indent is bigger than the regular indent.

![snacks-continuation-indent](https://github.com/user-attachments/assets/f6694ae9-e268-44c8-9d98-e841666e078a)

### Steps To Reproduce

Edit a file with a continuation indent, e.g.:

```java
public class Main {
  public static void main(String[] args) {
    System.out
        .append('a')
        .append('b');
  }
}
```

### Expected Behavior

Only one indent guide should be displayed under `System.out`. Other plugins (e.g., [`indent-blankline.nvim`](https://github.com/lukas-reineke/indent-blankline.nvim)) handle this case correctly.

![indent-blankline-continuation-indent](https://github.com/user-attachments/assets/4f29b948-ba56-4475-ae3e-e378b74a91ec)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      opts = {
        -- Indent guides without scope highlighting.
        indent = { scope = { enabled = false } },
      }
    },
    {
      "lukas-reineke/indent-blankline.nvim",
      main = "ibl",
      cond = false, -- Enable this and disable `snacks.nvim` for correct behavior.
      opts = {
        -- Indent guides without scope highlighting.
        scope = { enabled = false },
      },
    },
  },
})
```

**Comment by folke** [comment]
I think I added this correctly, but do let me know if you see unexpected results.

**Comment by andreihh** [comment]
Works great, thanks!
