### ISSUE TITLE
bug(input): create/delete file/dir in telescope-file-browser is broken with snacks.input

### ISSUE THREAD

**Issue by hengdashi** [folke/snacks.nvim#287]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

I use telescope-file-browser for create/delete files within nvim. Creating and Deleting the files used to work fine with dressing but with the new LazyVim 14 update dressing is replaced with snacks.input and that breaks the create/delete actions in telescope.

When I'm creating a new file within telescope-file-browser, I'm getting the following error messages:
```
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:90: Invalid window id: 1019
stack traceback:
	[C]: in function 'nvim_set_current_win'
	.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:90: in function <.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:89>
Error detected while processing TextChangedI Autocommands for "<buffer=28>":
Error executing lua callback: .../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:180: Invalid window id: 1019
stack traceback:
	[C]: in function 'nvim_win_call'
	.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:180: in function <.../.local/share/nvim/lazy/snacks.nvim/lua/snacks/input.lua:179>
```

### Steps To Reproduce

1. `:Telescope file_browser` to open the browser.
2. In insert mode, type `<A-c> (Alt + c)` to create a new file.

### Expected Behavior

A input window should show up on top of the telescope file browser window without closing the telescope file browser window (That's what dressing does).

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {
      input = {
        enabled = true,
      }
    } },
    -- add any other plugins here
    {
      'nvim-telescope/telescope.nvim', tag = '0.1.8',
      dependencies = { 'nvim-lua/plenary.nvim' }
    },
    {
      "nvim-telescope/telescope-file-browser.nvim",
      dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
    },
  },
})
```

**Comment by folke** [comment]
Should be fixed. File gets created, but file_browser doesn't update, is that normal?

**Comment by hengdashi** [comment]
hmm no, the file browser should update itself with the new file. I tried without the snacks plugin.

**Comment by folke** [comment]
The file does get created, which means the callback is successfully executed.
Will check the file_browser code to see what's up.

**Comment by folke** [comment]
found the problem. Fixed!
