### ISSUE TITLE
feature: Add `condition` option in statuscolumn.

### ISSUE THREAD

**Issue by spencer-thompson** [folke/snacks.nvim#288]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

No, just want to have some added functionality

### Describe the solution you'd like

[statuscol](https://github.com/luukvbaal/statuscol.nvim) has a feature where an optional `cond` is passed to each section of the statuscolumn. Additionally, if possible, it would be nice to configure the amount of extra space between the signs and the normal contents of the buffer (between line numbers and buffer content)

### Describe alternatives you've considered

A `padding` value could help.

### Additional context

A big motivation for this change is to integrate nicely with [neominimap.nvim](https://github.com/Isrothy/neominimap.nvim). This is an awesome plugin, that uses that condition to make the mini map have a more compact look.

Thanks for the awesome plugin. You are the man.

**Comment by folke** [comment]
Can you be more explicit on what you want here?
There's is no real padding. Numbers are full width. And there will be reserved space for git signs if you have those enabled.
So a padding param doesn't really make sense.

**Comment by spencer-thompson** [comment]
Of course, I think I don't have a huge understanding of how the plugin works. I just finished finals so I will have more time to explore. But what I mean, more specifically, is having a condition parameter to render signs, or the column itself.

Here is exactly why that is useful, from the `neominimap.nvim` wiki:

```lua
local function is_neominimap(arg)
    return vim.bo[arg.buf].filetype == "neominimap"
end

local function is_not_neominimap(arg)
    return not is_neominimap(arg)
end

return {
    "luukvbaal/statuscol.nvim",
    opts = function()
        local builtin = require("statuscol.builtin")
        return {
            setopt = true,
            relculright = true,
            segments = {
              -- These segments will be shown for normal buffers
              {
                  sign = {
                      namespace = { ".*" },
                      name = { ".*" },
                  },
                  condition = { is_not_neominimap },
              },
              {
                  text = {
                      builtin.lnumfunc,
                      " ",
                      builtin.foldfunc,
                  },
                  condition = { is_not_neominimap },
              },
              {
                  sign = {
                      namespace = { "gitsigns_" },
                  },
                  condition = { is_not_neominimap },
              },

              -- These segments will be shown for minimap buffers
              {
                  sign = {
                      namespace = { "neominimap_search" },
                      maxwidth = 1,
                      colwidth = 1, -- For more compact look
                  },
                  condition = { is_neominimap },
              },
              {
                  sign = {
                      namespace = { "neominimap_git" },
                      maxwidth = 1,
                      colwidth = 1,
                  },
                  condition = { is_neominimap },
              },
            },
        }
    end,
}
```

From my understanding, `neominimap.nvim` essentially duplicates the window but with braille to show a "mini map". So the code above allows `neominimap` to be more compact.

All in all this is probably not an important change, although it would allow me move from statuscol completely over to Snacks.

As far as the "padding", It would be nice if the statuscolumn had one less column, but after looking through the other issues, I can't be confident in ruling out that there isn't another plugin that is messing with the statuscolumn. I will be looking into that when I have time this week.

**Comment by folke** [comment]
Just added something where you can now have `left/right` be a function:

```lua
      statuscolumn = {
        left = function(win, buf)
          local is_neominimap = vim.bo[buf].filetype == "neominimap"
          return is_neominimap and { "mark" } or { "mark", "sign" }
        end,
        right = function(win, buf)
          local is_neominimap = vim.bo[buf].filetype == "neominimap"
          return is_neominimap and { "fold" } or { "fold", "git" }
        end,
      },

```
