### ISSUE TITLE
bug(indent): Not all listchars are displayed in case indent is enabled

### ISSUE THREAD

**Issue by pkropachev** [folke/snacks.nvim#291]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Ubuntu 20.04

### Describe the bug

Not all listchars are displayed in case indent is enabled.

### Steps To Reproduce

1. Set listchars.

```lua
local opt = vim.opt
opt.list = true
opt.listchars = {
  tab = ">-",
  trail = ".",
  nbsp = "¬",
  eol = "↲",
  space = ".",
  extends = ">",
  precedes = "<",
}
```

2. Open file in neovim.

![image](https://github.com/user-attachments/assets/162f4f49-c457-48a4-ad0c-d6cde005d0e7)

3. Disable indent `leader<ug>`.

![image](https://github.com/user-attachments/assets/0424e5d2-31a1-41f8-b9c2-bb31605df9e1)

### Expected Behavior

Listchars are displayed correct in case indent is enabled.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by hankertrix** [comment]
For some reason, the fix doesn't work for me.

![image](https://github.com/user-attachments/assets/62c6ac53-1585-4285-a46d-db04013401e4)

Here is my configuration for Snacks.nvim:

```lua
    {
        "folke/snacks.nvim",
        priority = 1000,
        lazy = false,
        opts = {
            bigfile = { enabled = true },
            quickfile = { enabled = true },
            statuscolumn = { enabled = true },
            indent = {
                enabled = true,
                scope = {
                    hl = "Label",
                },
            },
        },

        -- Key binds
        keys = {
            {
                "<Leader>x",
                function() Snacks.bufdelete() end,
                mode = "n",
                desc = "Close the current buffer",
            },
        },
    },
```

As per https://github.com/folke/snacks.nvim/commit/0e150f5510e381753ddd18f29facba14716d5669 and #296, here's my `listchars` configuration:

```lua
vim.opt.list = true
vim.opt.listchars = {
    lead = "·",
    trail = "•",
    multispace = "∅",
    nbsp = "‡",
    tab = "⇥»",
    precedes = "❮",
    extends = "❯",
    eol = "↵",
    -- eol = "⤶",
}
```

I'm not sure what I'm doing wrong here.

**Comment by hankertrix** [comment]
Never mind. I figured out the issue. Submitting a pull request.

**Comment by hankertrix** [comment]
Submitted #303 which fixes the issue.
