### ISSUE TITLE
bug: cannot pop any floating window with keybind

### ISSUE THREAD

**Issue by redbeardymcgee** [folke/snacks.nvim#299]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

nixos 24.11

### Describe the bug

A keymap defined with `expr = true` to run lua functions results in the below error.

```
E5108: Error executing lua: ...ir/pack/myNeovimPackages/start/snacks/lua/snacks/win.lua:339: E565: Not all
owed to change text or change window
stack traceback:
        [C]: in function 'nvim_open_win'
        ...ir/pack/myNeovimPackages/start/snacks/lua/snacks/win.lua:339: in function 'open_win'
        ...ir/pack/myNeovimPackages/start/snacks/lua/snacks/win.lua:433: in function 'show'
        ...ir/pack/myNeovimPackages/start/snacks/lua/snacks/win.lua:214: in function 'win'
        ...cial-rtp-entry-LuaConfig/lua/myLuaConf/opts_and_keys.lua:158: in function <...cial-rtp-entry-Lu
aConfig/lua/myLuaConf/opts_and_keys.lua:157>
```

`:lua Snacks.lazygit()` works as expected without any error. 

### Steps To Reproduce

1. Enable `vim.keymap.set("n", "<leader>gg", function() Snacks.lazygit() end, { expr = true, desc = "Lazygit" })`
2. Press keymap

### Expected Behavior

Launch floating terminal with lazygit (or other tool/buffer)

**Comment by folke** [comment]
What's your use-case to use `expr=true` here?

**Comment by folke** [comment]
You need to `vim.schedule` that call to create a window. expression keymaps can't alter the editor state.

**Comment by folke** [comment]
Or just don't use `expr=true`?

**Comment by redbeardymcgee** [comment]
Thanks for looking at this. I added the expr because I found it in `:help vim.keymap.set()` while hunting down another error with the keymap. That made it stop erroring on nvim startup, so I thought I'd solved the bug in my config. I apologize, I think I got myself mixed up between errors. Removing the `expr=true` now works as expected, so I definitely chased a red herring somewhere.

**Comment by folke** [comment]
`expr=true` is for keymaps that return a string to be executed as the keymap.
