### ISSUE TITLE
bug: undercurls applied to notification window

### ISSUE THREAD

**Issue by gfontenot** [folke/snacks.nvim#300]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macOS 15.1.1

### Describe the bug

Using the default config, I'm seeing undercurls in the notification window:

![Screenshot 2024-12-14 at 20 12 54](https://github.com/user-attachments/assets/f6f20cd9-72ff-49c3-ab4e-8f45c3b3d6b0)

I've seen the other bug describing a similar issue (#271), but this one is slightly different since the undercurls are being applied to the notification directly, not coming from the buffer underneath. I was previously using Noice without this issue happening.

### Steps To Reproduce

Unclear, all I did was add snacks.nvim and enable the notifier module.

### Expected Behavior

The notification should appear as it does in the documentation.

**Comment by folke** [comment]
That's your colorscheme that needs to be fixed.
