### ISSUE TITLE
feature: Dimming Splits + Changing Alpha Values

### ISSUE THREAD

**Issue by Jaxx497** [folke/snacks.nvim#301]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Unlike twilight.nvim, I did not see any options to change the alpha value of the dimmed text. Likewise, it would be really cool if we could apply the dimming to inactive buffers/splits. 

### Describe the solution you'd like

Implement the same dimming features that were seen in twilight.nvim

### Describe alternatives you've considered

(Still using multiple other plugins such as twilight.nvimi and tint.nvim)

### Additional context

N/A

**Comment by folke** [comment]
You can change the `SnacksDim` hl group.
things like `tint.nvim` are out of scope.
