### ISSUE TITLE
bug(scroll): clipboard paste issue with long text

### ISSUE THREAD

**Issue by tknightz** [folke/snacks.nvim#302]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

When pasting text from the system clipboard to Neovim with the Snacks.scroll enabled, the pasted text is truncated if it exceeds the current number of visible screen rows. The last few lines of the copied text are omitted from the pasted content.

### Steps To Reproduce

1. Open a file with Snacks.scroll enabled
2. Paste text from system clipboard by Ctrl+v (of course copied text has many lines than screen rows to trigger scroll)

### Expected Behavior

The entire copied text, including all lines, should be pasted without any truncation.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Can't reproduce. Please provide an actual text file that works with the repro (and update that to at least include scroll), if you want me too look at it.
