### ISSUE TITLE
bug(lazygit): reword commit via editor create new neovim proccess in floating window 

### ISSUE THREAD

**Issue by Sigthror** [folke/snacks.nvim#304]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1335+g3f1d09bc94

### Operating system/version

MacOS 14.4

### Describe the bug

I am using `nvim-remote` preset, and it is working as expected for the file edition, but if I try to reword a commit using the editor, a new Neovim instance spawns in a floating window. 
It also working as expected if I try to edit a commit by spawning LazyGit in the Neovim terminal, and in the case that I run a shell command in the LazyGit floating window (I have tested via `git commit --amend`).

### Steps To Reproduce

1. Open lazygit floating window
2. Chose any commit in commit panel
3. Reword (r) -> Open Menu (c-o) -> Open in editor (e)

### Expected Behavior

New tab appears in current Neovim instance

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Snacks just enables the preset, so this is out of scope.

**Comment by Sigthror** [comment]
Thank you for response, will try to adjust lazygit behavior.
Also very appreciate for your work, you are doing amazing stuff for neovim

**Comment by Sigthror** [comment]
Thank you for response, will try to adjust lazygit behavior.
Also very appreciate for your work, you are doing amazing stuff for neovim
