### ISSUE TITLE
bug(notifier): Notification is not transparent in case the current theme is transparent

### ISSUE THREAD

**Issue by pkropachev** [folke/snacks.nvim#317]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Ubuntu 20.04

### Describe the bug

Notification is not transparent in case the current theme is transparent.

I use `tokyonight` theme and explicitly set `transparent = true`.

```lua
-- tokyonight theme
{
  "folke/tokyonight.nvim",
  opts = {
    style = "moon", -- moon, storm, night, day
    transparent = true,
    styles = {
      sidebars = "transparent",
      floats = "transparent",
    },
  },
},
...
{
  "LazyVim/LazyVim",
  opts = {
    colorscheme = "tokyonight",
  },
},
```

![image](https://github.com/user-attachments/assets/527c34b2-9efa-4a31-b24b-2a00ed4f3b62)

### Steps To Reproduce

1. Use `folke/tokyonight.nvim` theme with explicitly set `transparent = true`.
2. Open neovim.
3. Any notifications are not transparent.

### Expected Behavior

Notifications are transparent in case using transparent theme.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That has been fixed already
