### ISSUE TITLE
feature: make `noautocmd` for `notifier` configurable

### ISSUE THREAD

**Issue by chrisgrieser** [folke/snacks.nvim#32]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

A few commits ago, I could still use a snippet like this one to add custom highlighting to any notification:

```lua
-- highlighting of filepaths and error codes
vim.api.nvim_create_autocmd("FileType", {
	pattern = "snacks_notif",
	callback = function(ctx)
		vim.defer_fn(function()
			vim.api.nvim_buf_call(ctx.buf, function()
				vim.fn.matchadd("WarningMsg", [[[^/]\+\.lua:\d\+\ze:]])
				vim.fn.matchadd("WarningMsg", [[E\d\+]])
			end)
		end, 1)
	end,
})
```

However, it appears since one of the recent commits, the notification windows are created with something like `noautocmd`, which makes it impossible to add custom highlights like that.

### Describe the solution you'd like

Make `noautocmd` configurable. Ideally, on a global as well as a per-notification basis.

### Describe alternatives you've considered

I am not aware of any other method to add such custom highlights.

### Additional context

Also, I added similar highlighting of notification content created by my plugin [tinygit](http://github.com/chrisgrieser/nvim-tinygit), which is also effectively disabled by this problem.

**Comment by folke** [comment]
ok, I'll revisit this. There's probably other use-cases as well that need that.
Reason I added `eventignore` is that setting the `filetype` in a buffer is the "hottest" line with profiling when rendering hundreds of notifications.

Will check why...

**Comment by folke** [comment]
This has been fixed in the meantime
