### ISSUE TITLE
feature: Change snacks check health WARNING to INFO.

### ISSUE THREAD

**Issue by Traap** [folke/snacks.nvim#324]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

An informational message should **not** be used when one decides to disable a built-in snacks feature. 

### Describe the solution you'd like

WARNNING should be **not** used when the user chose to disable a Snacks feature. 

Snacks.scope
- **WARNNING** setup {disabled} should be - **INFOMATION** setup {disabled}

Snacks.scroll
- **WARNNING** setup {disabled} should be - **INFOMATION** setup {disabled}

### Describe alternatives you've considered

Live with it (likely outcome) or stop using snacks.nvim (unlikely outcome).

**Comment by folke** [comment]
I don't agree. Sorry.
It's a warning so that users see that it's disabled. If it be ok, and something doesn't work a lot of users  will see ok and think their setup is fine. Users unfortunately are the worst when it comes to reading information.

**Comment by folke** [comment]
Yes, and thank you for that :)

**Comment by erikbloodshed** [comment]
Maybe don't show warning when the module has been disabled the user.

**Comment by aashish2057** [comment]
yeah I would love if it just didn't show up in checkhealth at all if it was disabled

**Comment by KaspervdHeijden** [comment]
Would be nice to be able to disable the warning if disabled. Maybe have a config setting for it?
