### ISSUE TITLE
bug: [indent] breakindent rendering is a bit weird

### ISSUE THREAD

**Issue by OmegaLambda1998** [folke/snacks.nvim#329]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1366+g022449b522 Build type: Release LuaJIT 2.1.1731601260

### Operating system/version

Linux omegalambda 6.12.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:30:31 +0000 x86_64 GNU/Linux

### Describe the bug

breakindent:
![2024_12_17_12_59_37](https://github.com/user-attachments/assets/b5890c3b-ad99-45ca-a23e-425397649756)

nobreakindent:
![2024_12_17_12_59_59](https://github.com/user-attachments/assets/b906f327-433a-4cef-b160-ea9cbc0863b6)

config:
```
opts.indent.indent = {
    enabled = opts.indent.enabled,
    priority = 200,
    char = ".",
    blank = nil,
    only_scope = false, -- only show indent guides of the scope
    only_current = false, -- only show indent guides in the current window
    hl = {
        "SnacksIndent1",
        "SnacksIndent2",
        "SnacksIndent3",
        "SnacksIndent4",
        "SnacksIndent5",
        "SnacksIndent6",
        "SnacksIndent7",
        "SnacksIndent8",
    },
}
opts.indent.scope = {
    enabled = opts.indent.enabled,
    priority = opts.indent.indent.priority,
    char = "",
    underline = true, -- underline the start of the scope
    only_scope = opts.indent.indent.only_scope,
    only_current = opts.indent.indent.only_current,
    hl = opts.indent.indent.hl,
}
opts.indent.chunk = {
    -- when enabled, scopes will be rendered as chunks, except for the
    -- top-level scope which will be rendered as a scope.
    enabled = opts.indent.enabled,
    -- only show chunk scopes in the current window
    only_scope = opts.indent.indent.only_scope,
    only_current = opts.indent.indent.only_current,
    priority = opts.indent.indent.priority,
    hl = opts.indent.indent.hl,

    char = {
        --- corner_top = "┌",
        --- corner_bottom = "└",
        corner_top = "╭",
        corner_bottom = "╰",
        horizontal = "─",
        vertical = "│",
        arrow = "─",
    },
}
```

### Steps To Reproduce

1. enable chunk
2. enable breakindent
3. write a really long line

### Expected Behavior

No sure how breakindent works so it may not be possible to render anything there, but I'd naively expect the chunk line to cross the indentation.

Also as a completely seperate question, can you set the highlight group of chunk to match the current scope highlight group, i.e if the scope is at level three, then the chunk colour should be `SnacksScope3` for instance.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I made some improvements to rendering indent guides, indent scopes and chunks when `breakindent` is set.
The only thing that's not possible to fix is the correct position of the ending `>` in chunks.
It will show as:
![image](https://github.com/user-attachments/assets/dcb646ba-c1b0-4d65-90ec-cd1bf6129b84)

But indent guides and the other parts of scopes and chunks will now be correct.
