### ISSUE TITLE
feature(notifier): ability to set foreground colors for notifications individually

### ISSUE THREAD

**Issue by theamallalgi** [folke/snacks.nvim#330]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When a warning message pops up, the foreground color is set to white (depends on the current theme), so is the case for every other type of notification.

### Describe the solution you'd like

a opt section with a function to edit specific highlight groups (like noice) would be really nice.

### Describe alternatives you've considered

Noice.nvim is probably the only alternative I'd use.

**Comment by folke** [comment]
You can inplement your own style. Check the docs / code
