### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by oldqin97** [folke/snacks.nvim#335]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 14.6.1

### Describe the bug

After I installed the snacks.nvim plug-in, I disabled some unnecessary shortcut keys in kyes, but the disabled shortcut keys can still be used.But the shortcut keys can be modified and used normally.

### Steps To Reproduce

<img width="378" alt="image" src="https://github.com/user-attachments/assets/cb9526e2-141b-44ea-b980-8dc5e6a8cf15" />

### Expected Behavior

I hope that like other plug-ins, I can directly disable some shortcut keys that I don’t need.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
This makes no sense. Snacks does not create any keymaps, so if you have something mapped, then that's you who'se doing that.
