### ISSUE TITLE
bug(indent): constant error throwing when scrolling a text file

### ISSUE THREAD

**Issue by pedrog14** [folke/snacks.nvim#339]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1369+gb03e790cdd

### Operating system/version

Arch Linux 

### Describe the bug

In some text files i get the following error when scrolling, even with jk movement, while indent is activated (already tested disabling scope, and using filters, same result):
![20241217-161925](https://github.com/user-attachments/assets/1c1f4101-f05e-4350-868b-3aac7f801de0)

Only happens when indent is enabled.

### Steps To Reproduce

- Open a random text file while using snacks.nvim with indent enabled (preferred to test with a Apache license text file, as i only got this error consistently in it).

### Expected Behavior

- The text should scroll normally, with no error throwing.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { indent = { enabled = true } } },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I obviously don't have this error so please share your config and a text file that triggers it with the location or actions in that file

**Comment by pedrog14** [comment]
[Here](https://github.com/user-attachments/files/18172642/LICENSE.txt) is the file. It should give you the same error with the given repro config.

**Comment by pedrog14** [comment]
```
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
``` 
You can test this snippet from the Apache License file, it's the only text example i could give with this problem
