### ISSUE TITLE
bug: visual issues in `snacks.indent` after removal of blank overwrites

### ISSUE THREAD

**Issue by Redoxahmii** [folke/snacks.nvim#344]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux

### Describe the bug

There is visual discrepancies when there is a line for diagnostic errors such as (not sure if this is the desired result) :
![image](https://github.com/user-attachments/assets/4def65e7-00ec-4959-b8d7-d69d89c84e6f)
 
 In other themes the visual mode has issues as well causing blank lines between them :
![image](https://github.com/user-attachments/assets/ed258ede-f7b0-4eb0-b46c-a99f01f98baf)

If this is an issue related to the theme I will close and a little nudge in the right direction is appreciated.
Thank you for your work as always.

### Steps To Reproduce

1. Enter a buffer and see error diagnostic line.

### Expected Behavior

Show normally without the visual hitches.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Can't reproduce this at all, unless I'm missing a reproduction step?

![image](https://github.com/user-attachments/assets/7551cb87-25dd-40b8-9bef-f8a4b8046fcf)
![image](https://github.com/user-attachments/assets/b7146eef-fefb-4899-a5d7-3cf26c0ffb01)

**Comment by folke** [comment]
That second issue is because the default hl group "SnacksIndent" defaults to `NonText`.
Your NonText apparently sets a background.
So just define `SnacksIndent`.
That first issue is not possible to fix. That's because those initial cols, somehow also show the underline, but that's not the `SnacksIndent` won't have an `sp` value set, so no unerline. Not possible to fix.

**Comment by Redoxahmii** [comment]
Thank you for the quick response I do have `SnacksIndent` defined and it sets a color and I've tested with passing `none`  for bg as well but it still replicates the same for me.
```lua
    SnacksIndentScope = { fg = c.violet, nocombine = true },
    SnacksIndent = { fg = c.base03, nocombine = true },
```
I am a bit lost on this for the time but I will look into it more.

**Comment by folke** [comment]
Not home right now, but will check a certain extmark option that might fix this.

**Comment by Redoxahmii** [comment]
[solarized-osaka.nvim](https://github.com/craftzdog/solarized-osaka.nvim)

**Comment by folke** [comment]
The issue is that the theme defines `Visual` as `inverse = true`.

**Comment by Redoxahmii** [comment]
Thank you for the info seems like it can't be solved at the moment or would need to remove `reverse = true` for `Visual` which might not be desired by the maintainer.

**Comment by Redoxahmii** [comment]
I can't really think of a workaround for this so i guess it has to be as it is or people can use `opts.on_highlights` to change this value if they tend to stick with `snacks.nvim`.

**Comment by folke** [comment]
You can just change it to what the reverse would be no?
So just switch fg/bg of normal for `Visual`

**Comment by Redoxahmii** [comment]
I didn't find `VisualNormal` in `hl-Normal` or `hl-Visual` or am i missing something?
I'm not that familiar with hl groups yet.

**Comment by Redoxahmii** [comment]
This screenshot should highlight properly how in visual mode it reverses the characters and they are visible :
![image](https://github.com/user-attachments/assets/9d5924d4-76b4-4bec-80df-e2434c035150)

removing `reverse  = true` and setting a hard set bg takes away that different color highlighting effect and hard setting `fg` as well will make it a single color.
If there was a `VisualNormal` group it could be set to reverse so that `Visual` remains normal and you can apply the reverse on only the text but that does not seem to exist.
Is it possible to reverse only the `fg` of `Visual` cause i couldn't find anything.

**Comment by folke** [comment]
no idea and really out of scope for the indent plugin.
I add the extmarks the way I should add them

**Comment by Redoxahmii** [comment]
Understandable thank you.
