### ISSUE TITLE
feature: Be able to exit zen mode using q

### ISSUE THREAD

**Issue by TheseusGrey** [folke/snacks.nvim#347]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Overview of the problem:
- Wanted to be able to exit out of zen mode with `q` using an `autocmd` similar to [the one found in lazyvim](https://github.com/LazyVim/LazyVim/blob/28d3ee49709978eb350e5c6bfe1f2ce36138c1d3/lua/lazyvim/config/autocmds.lua#L53)
- checking the filetype with `:echo &ft` shows the originally detected filetype of the buffer, for example:
  - for `some_file.lua` the filetype would be `lua`
  - for `another_file.txt` the filetype would be `txt`

This makes it difficult to close the buffer since there isn't a consistent filetype for the `autocmd` to use. I know 

### Describe the solution you'd like

To ideas came to mind:
- Add option to the config for closing with `q`
- Set the filetype to `zen` when toggling zen mode.

I've tried the second option in my own config and it breaks the highlighting and can cause the buffers to get into a weird state since it unlists the original buffer as well as the zen window:

```lua
-- close some filetypes with <q>
vim.api.nvim_create_autocmd("FileType", {
  group = augroup("close_with_q"),
  pattern = {
    "zen",
    -- ...
  },
  callback = function(event)
    vim.bo[event.buf].buflisted = false
    vim.keymap.set("n", "q", "<cmd>close<cr>", {
      buffer = event.buf,
      silent = true,
      desc = "Quit buffer",
    })
  end,
})
```
Then inside the `snacks.nvim` config
```lua
{
  "<leader>zm",
  function()
  -- set filetype for active buffer
   -- vim.bo[vim.fn.bufnr('%')].filetype = "zen" -- same result as line below
    vim.bo[0].filetype = "zen"
    Snacks.zen()
    Snacks.dim()
  end,
  desc = "Toggle focus editing",
},

```

### Describe alternatives you've considered

Tried the basic solution I showed above, but if there's a way to get the option that preserves the highlighting and doesn't unlist the original buffer that would be ideal.

### Additional context

It's not a deal breaker since I can just use the same keys again to exit the zen mode. But having hard wired muscle memory that `q` will quit the current thing it would definitely be a nice to have.

**Comment by dpetka2001** [comment]
You can just do the following
```lua
{
  "folke/snacks.nvim",
  opts = {
    styles = {
      zen = {
        keys = { q = "close", },
      },
    },
  },
}
```

**Comment by TheseusGrey** [comment]
Ah thank you, I had assumed the `styles` sections was purely for visual stuff so didn't think to get the options there :sweat_smile:
