### ISSUE TITLE
bug: marks in statuscolumns only appear after cursor move

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/snacks.nvim#349]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS 13.6.1 Ventura

### Describe the bug

When setting marks the statuscolumn shows the corresponding mark entry only after cursor move. If the cursor stands still (after setting the mark, say `ma`) then the statuscolumn doesn't show the mark being set.

### Steps To Reproduce

1. set a mark with `ma`
2. stand still with the cursor
3. the mark doesn't appear in the statuscolumn

See below a screen recording of the behaviour

![Kapture 2024-12-18 at 17 21 32](https://github.com/user-attachments/assets/9ff5e0d1-d960-460c-9737-95d64348e74f)

you can see that the mark only appears when the cursor moves away from the initial character.

### Expected Behavior

I would expect the mark to appear without having to move the cursor.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = "number"
require("lazy.minit").repro({
    spec = {
        {
            "folke/snacks.nvim",
            opts = {
                statuscolumn = { enabled = true, right = { "sign", "git" }, left = { "mark", "fold" }, refresh = 5 },
            },
        },
        -- add any other plugins here
    },
})
```

**Comment by folke** [comment]
Yes, that's an optimization.
Buffer data only gets refreshed at most `opts.refresh` ms (defaults to `50`)
When the cursor moves, you trigger a `redraw` and will see the new information.

Fetching all data on redraw each and every time, is really not great in terms of performance,
so I'd like to keep it like this.

Setting it to `0` might fix your issue, but again, would not recommend.

**Comment by gennaro-tedesco** [comment]
I see, thank you for explaining! Yes, it makes sense, I will keep it as is!
