### ISSUE TITLE
bug: snacks words highlighting lags behind when navigating

### ISSUE THREAD

**Issue by dotfrag** [folke/snacks.nvim#35]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

Something's up with Snacks.words highlighting. When you move the cursor, the highlighting lags behind. It's difficult to explain but it feels like the debounce logic is not working as expected.

Here's a video => https://streamable.com/0juxd1

Sample file (`test.lua`):

```lua
local aaaa = 1
local bbbb = 1
local cccc = 1
local dddd = 1

-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable
-- blank lines to make problem noticable

local eeee = 1
local ffff = 1
local gggg = 1
local hhhh = 1
local jjjj = 1
```

### Steps To Reproduce

1. Use sample file from above
2. Move cursor to 'a'
3. Hold `j` to go down
4. See how the highlights moves to `bbb` and stays highlighted while still navigating down

### Expected Behavior

When cursor is on `aaaa`, it should be highlighted. As soon as you start navigating, the highlight should disappear and stay gone until navigating stopped AND debounce timer is expired.

### Repro

> LazyVim starter. I couldn't use the minimal repo because it needs lsp config etc.

**Comment by folke** [comment]
Can;t reproduce. Do you have another plugin that triggers `vim.lsp.buf.document_highlight()` or an autocmd you created?

**Comment by folke** [comment]
or another plugin like illuminate?

**Comment by dotfrag** [comment]
It's LazyVim starter, default config, LazyVim spec with `dev=true` and I'm latest commit. So I would guess no?

**Comment by folke** [comment]
Can't reproduce. You probably just do `j` too slow. Increase the debounce

**Comment by dotfrag** [comment]
Okay thanks for checking.
