### ISSUE TITLE
bug: completion in input

### ISSUE THREAD

**Issue by skoch13** [folke/snacks.nvim#350]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1376+g738320188f

### Operating system/version

MacOS 15.2

### Describe the bug

I saw that there is a commit 37038df for disabling completion suggestions for `blink.cmp`, but I suppose it should be also disabled for `nvim-cmp`

![Screenshot 2024-12-18 at 18 24 24](https://github.com/user-attachments/assets/22ebcae1-4afa-4e2a-b258-45386d43ddc4)

### Steps To Reproduce

1. use LazyVim with `nvim-cmp` extra enabled
2. try to rename a variable

### Expected Behavior

No completion in input

**Comment by folke** [comment]
HAs been fixed already, but you need blink main, or wait for a new blink release. 
See related other issues in this repo.

**Comment by skoch13** [comment]
Like I mentioned, I use nvim-cmp

**Comment by folke** [comment]
Just changed it so that the buftype is `prompt`, which nvim-cmp excludes.

**Comment by dhananjaylatkar** [comment]
Hi @folke -

same issue is seen when using Snacks.picker and mini-completion -

![Image](https://github.com/user-attachments/assets/ed42d446-25c3-4fee-b44c-bf8854417254)

**Comment by folke** [comment]
Not a snacks issue.

**Comment by dhananjaylatkar** [comment]
If anyone is facing same issue, you can use this to disable mini.completion in snacks picker -

```lua
vim.cmd([[au FileType snacks_picker_input lua vim.b.minicompletion_disable = true]])
```

**Comment by vtmx** [comment]
I has the sema problem in native auto-complete in version 0.12, fix with code:

```lua
vim.pack.add({ 'https://github.com/folke/snacks.nvim' })

require('snacks').setup({
  picker = { enable  = true }
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'snacks_picker_input',
  callback = function(event)
    vim.o.autocomplete = false
    vim.api.nvim_create_autocmd('BufLeave', {
      buffer = event.buf,
      once = true,
      callback = function()
        vim.o.autocomplete = true
      end
    })
  end
})
```
