### ISSUE TITLE
feature: Lazygit should keep the current process running in the background

### ISSUE THREAD

**Issue by itse4elhaam** [folke/snacks.nvim#351]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I was trying to push to a repo and it took longer than expected, I closed lazy git by pressing q and the push got terminated.

### Describe the solution you'd like

Ideally, it should keep its work up in the background if any operation(s) such as commit/pull/push is in progress. This is especially true for remote operations since they take more time.

### Describe alternatives you've considered

I am just forced to use the CLI at times for pushing the code when I know its gonna take longer.

### Additional context

https://github.com/LazyVim/LazyVim/discussions/1287
https://github.com/kdheepak/lazygit.nvim/issues/143

**Comment by folke** [comment]
You can just do `:close` on the lazygit window and then when you open it again it will show where you were.
You can also create a keymap that toggles lazygit of course.
