### ISSUE TITLE
bug: Scratch stuck open when opening a buffer from within

### ISSUE THREAD

**Issue by Joniator** [folke/snacks.nvim#354]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Sample alpine docker image from LazyVim starter

### Describe the bug

When opening a new buffer from within the scratch, it gets stuck in the foreground and cant be closed as long as the opened buffer is selected. So switching to another buffer/closing the opened buffer lets you toggle it again.

### Steps To Reproduce

1. Open a scratch (S1)
2. Add a filename (e.g. `/etc/passwd`)
3. Open the file with `gf`
4. Toggling the scratch does open a new scratch (S2) on top of the first one.
5. q/Toggling does close S2, but S1 stays open and can't be closed
6. Switch away from/delete opened buffer
7. Toggle the scratch to hide S1

### Expected Behavior

The scratch does not get stuck in an hard to close state while a new buffer is opened

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      keys = {
          { "<space>.",  function() Snacks.scratch() end, desc = "Toggle Scratch Buffer" },
          { "<space>S",  function() Snacks.scratch.select() end, desc = "Select Scratch Buffer" },
      }
    },
  },
})
```

**Comment by folke** [comment]
just go back to the scratch window? It can still be closed.
Use `<c-w>w`
