### ISSUE TITLE
Option to keep terminal open when cmd completes

### ISSUE THREAD

**Issue by scottmckendry** [folke/snacks.nvim#36]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When running a terminal command that writes to stdout and then exits immediately, you’re not given any opportunity to see the output. The terminal window just closes immediately.

### Describe the solution you'd like

Ideally, there would be a way to keep the terminal open after the cmd exits. Toggleterm does something like this by default when it keeps your cursor in the current buffer, executes the command in the terminal window and leaves it open so you can see the results. Great for running `make` and executing tests etc. 

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
`interactive=false`
