### ISSUE TITLE
feature (Lazygit) : Ability to bring up lazygit with git root of current buffer

### ISSUE THREAD

**Issue by obarbier** [folke/snacks.nvim#364]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

No. It it's an enhancement to current functionality

### Describe the solution you'd like

As a user of Snacks.nvim i want to be able to open lazygit from current buffer so that i can work on multiple git repo at the same time. Currently i have to cd into the repo i want to bring lazygit popup and then bring lazygit. This functionality would be similar to kdheepak/lazygit.nvim :LazyGitFilterCurrentFile<CR>

### Describe alternatives you've considered

Cd into the repo (or bring up Neogit) and then bring lazygit

### Additional context

Work flow involve having a root directory where i put all related project. i usually start nvim from that directory. current lazygit make it difficult to manage multi repo project

Thank you for looking into this

**Comment by xian-wen** [comment]
I was wondering whether it is possible to move the `LazyVim.root()` and `LazyVim.root.git()` logic into something similar to `Snacks.root()` and `Snacks.root.git()`, which would solve this problem, as well as so many keymap settings that require the root directory.

**Comment by folke** [comment]
`:lua Snacks.lazygit({cwd = Snacks.git.get_root()})`
