### ISSUE TITLE
feature: equivalent to `:bwipeout` so `:e #` doesn't immediately re-open the deleted buffer

### ISSUE THREAD

**Issue by scottmckendry** [folke/snacks.nvim#38]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I replaced [my own function](https://github.com/scottmckendry/Windots/blob/d0bf38acb69853bb4c046b12846b6fd42b804cad/nvim/lua/core/utils.lua#L23) with the snacks.nvim bufdelete implementation. Since my own way had a few issues. 

So far so good. However, I've found that navigating to other "other" buffer with `:e #` reopens the buffer that was just deleted. 

### Describe the solution you'd like

An option to pass to bufdelete that prevents the current buffer from re-opening when using `:e #`. Or make it the default (if this behaviour is not intentional).

**Comment by scottmckendry** [comment]
Thanks @folke! 

I think something's not quite right. When I pass `{ wipe = true }` to `bufdelete` it doesn't delete the buffer that is currently focussed, but rather one of the other open buffers instead.

**Comment by folke** [comment]
How can I repdoduce this?
What's your config and how do you call bufdelete?

**Comment by folke** [comment]
Sorry, fixed now :)
