### ISSUE TITLE
bug: `2<C-/>` does not open the second terminal in root directory

### ISSUE THREAD

**Issue by xian-wen** [folke/snacks.nvim#385]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

WSL2 Ubuntu 24.04

### Describe the bug

When I press `<C-/>`, the first terminal is opened in the root directory. However, when I press `2<C-/>`, the second terminal is opened in the current working directory.
![image](https://github.com/user-attachments/assets/3d26672a-8d67-4ede-b399-a11fb6664dee)

### Steps To Reproduce

1. Press `<C-/>` to open the first terminal.
2. Press `<Esc><Esc>` to be back to normal mode.
3. Press `2<C-/>` to open the second terminal.

### Expected Behavior

Pressing `2<C-/>` opens the second terminal in the root directory, just like the first one.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
You're pressing `2<C-/>` from the terminal right? If you press it from the buffer instead it will open correctly at the root directory. The root directory is calculated based on LSP root or cwd. Since, you're in a terminal buffer and there's no LSP attached to it, the `cwd` will be used instead. That's what you observe.

**Comment by xian-wen** [comment]
Sorry, I have to be back to normal mode first with `<Ecs><Esc>`. "Steps To Reproduce" is updated.

**Comment by xian-wen** [comment]
My root directory is got by calling `Snacks.git.get_root()`, which seems to have nothing to do with lsp, `2<C-/>` in the terminal normal mode also failed to open the second terminal in the root directory.
