### ISSUE TITLE
bug: Indent could not be customized

### ISSUE THREAD

**Issue by hrdm** [folke/snacks.nvim#389]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.3

### Operating system/version

MacOS Sequoia Versionar 15.2

### Describe the bug

Hello folke,
I've noticed that it's not possible to customize Snack.indent at the moment, for instance, if the `char` option of `indent` (`scope`, `chunk`, or other) is changed in the custom user files, this change doesn't have any effects.
This issue does not only affect the `char` option, **but also** other options.

In the next screenshot the `char` options is changed to another character, then the config is reloaded, and another nvim session is open one more time, but the change is not visible:
![issue](https://github.com/user-attachments/assets/22d065bf-8891-44fe-999d-d93e34e7bf2a)
 
 So, I've checked the `snacks` code in `snacks.nvim/lua/snacks/indent.lua` that (for example) for indent, the code just test the `enable` option, and then the default configuration is loaded.
![issue2](https://github.com/user-attachments/assets/261d0707-1af1-41ef-86b3-2234cf490902)
 
I think, this is a minor issue, But I still tried to communicate it.
Thank for your time

### Steps To Reproduce

1. In the `nvim/lua/plugins/ui.lua', I've tried to customize the snacks indent options:
``` lua
{
  "folke/snacks.nvim",
  ---@type snacks.Config
  opts = {
    ---@class smacks.indent.Config
    ---@field enabled? boolean
    indent = {
      enabled = true,
      char = "▏",
    },
    scope = {
      enabled = true,
      underline = true,
      char = "▏",
    },
  },
}

```
2. Then, I reloaded the configuration and open another nvim session.
3. The changes do not have any effects.
![issue](https://github.com/user-attachments/assets/24eac20c-a20e-4e11-b937-0d87f353af4a)
 

### Expected Behavior

- The expected behavior is that the custom changes are visible.
- I've done some direct changes in `~/.local/share/nvim/lazy/snacks.nvim/lua/snacks/indent.lua` with success:
```lua
local defaults = {
  indent = {
    priority = 1,
    enabled = true, -- enable indent guides
    char = "▏", -- **Here**
    ...
  scope = {
    enabled = true, -- enable highlighting the current scope
    priority = 200,
    char = "▏", -- **Here**
    underline = true, -- **Here**
  ...
}
```

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
You're using wrong syntax. It should be
```lua
opts = {
  indent = {
    indent = { -- whatever you want },
    scope = { -- whatever you want },
  },
}
```

**Comment by hrdm** [comment]
Hey dpetka2001, thanks a lot, it works!

**Comment by hrdm** [comment]
BTW, is it possible to exclude some files (for example markdown) from indenting ?

**Comment by hrdm** [comment]
Hi @dpetka2001, you’re amazing! Thanks so much for your help! The snacks indent is finally working perfectly here! 😉
```lua
      indent = {
        indent = {
          enabled = true,
          char = "▏",
        },
        scope = {
          enabled = true,
          underline = true,
          char = "▏",
        },
        filter = function(buf)
          local b = vim.b[buf]
          local bo = vim.bo[buf]
          local excluded_filetypes = {
            markdown = true,
            text = true,
          }
          return vim.g.snacks_indent ~= false
            and b.snacks_indent ~= false
            and bo.buftype == ""
            and not excluded_filetypes[bo.filetype]
        end,
      },
```
