### ISSUE TITLE
bug: snacks.statuscolumn triggered when it is disabled

### ISSUE THREAD

**Issue by zivkovicn** [folke/snacks.nvim#392]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1734355927

### Operating system/version

MacOS 15.2

### Describe the bug

When testing the snacks.profiler plugin, I've noticed that `snacks.statuscolumn` is being triggered multiple times, even if I disabled it.

### Steps To Reproduce

1. Start the snacks.profiler
2. Move up and down left and right with through the file
3. Stop the snacks.profiler
4. Look at the summary output

### Expected Behavior

When snacks.statuscolumn is disabled, it shouldn't trigger at all.

Here is the screenshot from profiler:
    
<img width="1245" alt="Screenshot 2024-12-26 at 1 51 42 AM" src="https://github.com/user-attachments/assets/5a927042-2733-4d8b-bd63-5156aafaf6c7" />

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { statuscolumn = { enabled = false } } },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Are you using LazyVim? If yes, then the statuscolumn is set via the options. So, to disable it you could do in your `options.lua` file `vim.opt.statuscolumn = ""`.

**Comment by zivkovicn** [comment]
@dpetka2001 thanks! I didn't know that, I was thinking that when we pass `enabled = false` that it will disable it. Closing!
