### ISSUE TITLE
bug: Zen mode is closed upon toggling the terminal

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [folke/snacks.nvim#398]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM 0.10.2

### Operating system/version

Arch linux kernel 6.12.4-zen1-1-zen

### Describe the bug

opening the snacks terminal closes the zen mode.

### demonstration

https://github.com/user-attachments/assets/8c249cde-fc10-4ce4-a3d1-c283949d1853

### Steps To Reproduce

1. go into zen mode
2. open snacks terminal
3. zen mode is closed

### Expected Behavior

snacks terminal does nothing to zen mode and it is kept open.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
That is intended behavior as the [code here indicates](https://github.com/folke/snacks.nvim/blob/98df370703b3c47a297988f3e55ce99628639590/lua/snacks/zen.lua#L198-L210). Whenever you enter another window such as a terminal and it's not a floating window then zen mode exits.

**Comment by mohammad-amin-khajeh** [comment]
I see.

I can see how this would be helpful in some contexts; but in this case isn't there a way to get around this behavior?
or at least some hacky way to get the job done?

In my workflow I tend to open and close the terminal a lot and so having to turn on zen mode every single time defeats the whole purpose of it.

**Comment by dpetka2001** [comment]
Just open your terminal as a float window instead, since that doesn't seem to quit zen mode?

**Comment by mohammad-amin-khajeh** [comment]
Yes I ended up doing that thanks for the suggestion.

For anyone wondering how to do it, your snacks config should look something like this:

```lua
opts = {
    terminal = {
      ---@class snacks.terminal.Config
      ---@field win? snacks.win.Config
      ---@field override? fun(cmd?: string|string[], opts?: snacks.terminal.Opts) Use this to use a different terminal implementation

      win = { position = "float" },
    },
  }
```

**Comment by dpetka2001** [comment]
By doing it this way, you're changing the behavior for all terminal windows that are created with Snacks. This might be the behavior you want or might not. For example lazygit also opens in a terminal window but it's opened in a float window either way by default. 

Personally I prefer to put these custom changes into `styles` myself, because that way only the windows with the selected style will be affected. So, I do 
```lua
opts = {
  styles = {
    terminal = {
      position = "float",
    },
  }
}
```
