### ISSUE TITLE
feature: Cyclic Snacks.words.jump

### ISSUE THREAD

**Issue by lomes0** [folke/snacks.nvim#399]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

When using Snacks.words.jump, to iterate back to first reference from the last, it is needed to cycle through all references.

### Describe the solution you'd like

Make Snacks.words.jump cyclic.

### Describe alternatives you've considered

A wrapper around Snacks.words.jump function.

**Comment by dpetka2001** [comment]
That is already possible. As you can see [here](https://github.com/folke/snacks.nvim/blob/98df370703b3c47a297988f3e55ce99628639590/lua/snacks/words.lua#L128) `Snacks.words.jump` accepts a second parameter `cycle` which is boolean and does what you want. You just have to incorporate that in your mappings.

**Comment by lomes0** [comment]
I feel ashamed.
