### ISSUE TITLE
bug: Can not update a notify by using vim.notify(msg, {replace = id}) after enable snacks.nvim

### ISSUE THREAD

**Issue by MayDomine** [folke/snacks.nvim#42]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Mac14,7

### Describe the bug

After enable snacks.nvim, I can not use {repalce = id} to update a existing notify window.

### Steps To Reproduce

1. call a lua script in vimscript  ` let g:log_id = luaeval('vim.notify([[' . g:_msg . ']], "warn", {title = "vim-arsync", replace = ' .. g:log_id .. ', animate = false ,icon = "' .. g:current_frame .. '"})').id`
2. update it by using `call luaeval('vim.notify([[' . l:success. ']], "info", {title = "vim-arsync", replace = ' .. g:log_id .. ', icon = "", timeout = 1000})')`

### Expected Behavior

After enable snacks.nvim, I can use {repalce = id} to update a existing notify window.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by MayDomine** [comment]
I fix this this by using {id = id}.
https://github.com/folke/snacks.nvim/blob/main/docs/notifier.md

**Comment by folke** [comment]
fyi: I also added backward compatibilty with nvim-notify's `replace` in the meantime...
