### ISSUE TITLE
bug: notify window gained focus unexpectedly

### ISSUE THREAD

**Issue by AbaoFromCUG** [folke/snacks.nvim#44]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

ArchLinux 6.11.6-arch1-1

### Describe the bug

I use the [Advanced LSP Progress](https://github.com/folke/snacks.nvim/blob/main/docs/notifier.md#-examples) example config. which will show progress when lsp server need show progress(such as init or format).

Then I map `vim.lsp.buf.format()` to `<Space>f` to format buffer code.  When I format the code with `<Space>f`, the notify window will sometimes get focus unexpectedly (cursor move to notify window).

I don't known the cause of my issue, maybe some `option` or plugins, I use
* which-key.nvim
* nvim-lspconfig.nvim
* snacks.nvim

A workaround maybe provides a callback of `on_open` of window, like https://github.com/rcarriga/nvim-notify/issues/28

Thanks for your plugin

### Steps To Reproduce

* config lsp progress with notifier
* map `vim.lsp.buf.format()` to `<Space>f`
* press `<Space>f` 

### Expected Behavior

Notify window would don't gained focus

### Repro

```lua
I tried to configure repro.lua, but I couldn't reproduce.
```

**Comment by folke** [comment]
Sorry, but this is not caused by notifier.
