### ISSUE TITLE
bug: bigfile snack is dependent on notifier snack?

### ISSUE THREAD

**Issue by andrewferrier** [folke/snacks.nvim#5]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1103+g04274a4173

### Operating system/version

Arch Linux

### Describe the bug

Thanks for snacks, looks like a great selection of tools, just getting used to it!

I assumed (perhaps incorrectly) that you intended for the snacks to be independent, but it looks like the bigfile snack is dependent on the notifier snack. If I load a bigfile, I get a notification that's come from the notifier snack, even if I don't want to use notifier. Perhaps bigfile should be using vim.notify() instead and allow notifier to handle it only if enabled?

### Steps To Reproduce

1. Enable bigfile, disable notifier snack in config
2. Load a big file
3. Observe notifier notification

### Expected Behavior

Conventional notification in cmdline

### Repro

```lua
return {
    "folke/snacks.nvim",
    lazy = false,
    opts = {
        bigfile = { enabled = true }
        notifier = { enabled = false },
    }
}
```

**Comment by andrewferrier** [comment]
Huh, just updated and this has gone away. I think this might have been fixed by your fix for #2...

**Comment by folke** [comment]
Yep, indeed. disabling actually didnt work :)

**Comment by andrewferrier** [comment]
Thanks. Sorry for the false alarm.
