### ISSUE TITLE
bug: vim.notify triggers of snacks notifier continuously. 

### ISSUE THREAD

**Issue by dangdd2003** [folke/snacks.nvim#50]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Neovim stable release 0.10.2

### Operating system/version

Arch Linux

### Describe the bug

First of all, i'm really sorry that i don't have much experience in writing lua function, so the code I used was from the maintainer, folke's dotfiles. Really thank you for this function.

I used the `cowboy()` function in folke's neovim dotfiles, and i don't know why snacks spam the notification. As far as i know, `pcall()` will stop this spamming as same as when using vim.notify with `rcarriga/nvim-notify. I think this could be a bug.

![image](https://github.com/user-attachments/assets/0bc89acb-e9be-43bd-a26c-d620067a3b66)

### Steps To Reproduce

1. Using the same function `cowboy()` in folke's dotfiles to trigger vim.notify
2. Spaming `j,k,l,h,-,+` makes snacks keep spamming notification.

This is the function if you need the reference.
```lua
 function M.cowboy()
  ---@type table?
  local id
  local ok = true

  for _, key in ipairs({ "h", "j", "k", "l", "+", "-" }) do
    local count = 0
    local timer = assert(vim.uv.new_timer())
    local map = key
    vim.keymap.set("n", key, function()
      if vim.v.count > 0 then
        count = 0
      end
      if count >= 20 and vim.bo.buftype ~= "nofile" then
        ok, id = pcall(vim.notify, "Hold it, Cowboy!", vim.log.levels.WARN, {
          icon = "🤠",
          -- title = "Heyyyyy!!!",
          replace = id,
          keep = function()
            return count >= 20
          end,
        })
        if not ok then
          id = nil
          return map
        end
      else
        count = count + 1
        timer:start(2000, 0, function()
          count = 0
        end)
        return map
      end
    end, { expr = true, silent = true })
  end
end
```

### Expected Behavior

It should not be notification spamming as in the image. Only one shows up.

**Comment by folke** [comment]
Updating snacks probably fixes it since I just added support for nvim-notify's `replace`.

If not, you can use:

```lua
function M.cowboy()
  ---@type table?
  local ok = true
  for _, key in ipairs({ "h", "j", "k", "l", "+", "-" }) do
    local count = 0
    local timer = assert(vim.uv.new_timer())
    local map = key
    vim.keymap.set("n", key, function()
      if vim.v.count > 0 then
        count = 0
      end
      if count >= 10 and vim.bo.buftype ~= "nofile" then
        ok = pcall(vim.notify, "Hold it Cowboy!", vim.log.levels.WARN, {
          icon = "🤠",
          id = "cowboy",
          keep = function()
            return count >= 10
          end,
        })
        if not ok then
          return map
        end
      else
        count = count + 1
        timer:start(2000, 0, function()
          count = 0
        end)
        return map
      end
    end, { expr = true, silent = true })
  end
end
```

**Comment by dangdd2003** [comment]
Thanks for the fast reply, it works.
