### ISSUE TITLE
feature: Direct URL Retrieval for Current File and Line in `gitbrowse`

### ISSUE THREAD

**Issue by nsoufian** [folke/snacks.nvim#51]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

I'm often in situations where I need to share a link to a specific line of code with my coworkers. Currently, gitbrowse requires me to open the file in the browser, find the line, and then manually copy the link. This process is a bit tedious when done frequently and disrupts my workflow. I’d love a more direct way to get a link to a specific line without needing to open a browser.

### Describe the solution you'd like

A method like `copyToClipboard` in gitbrowse would allow me to retrieve the URL of the current file and line and copy it directly to the clipboard. An alternative could be enhancing `get_url` to return the URL for the current file and line without requiring a repository argument. This way, I could quickly generate and copy the link for easy sharing.

### Describe alternatives you've considered

- Manually opening the file in the browser, finding the line, and copying the link. This works but is time-consuming.
- Writing a custom script outside gitbrowse to achieve the same functionality, but I’d prefer this as part of snacks to keep my workflow consolidated in Neovim.

### Additional context

If this feature aligns with the goals for gitbrowse, I’d be happy to contribute to its implementation. Any guidance on the preferred approach or API design would be appreciated. Thanks again for creating `snacks`—it’s a fantastic addition to the Neovim ecosystem!

**Comment by folke** [comment]
just pass `open = function(url)...end` as an option?

**Comment by nsoufian** [comment]
@folke Thanks for the suggestion!
I also want to use the open functionality to launch the URL in the browser. My current configuration is as follows:
```
open = function(url)
  vim.system({ 'explorer.exe', url })
end,
```
owever, I’m looking for a way to make this open function versatile, so it can both open the URL in the browser and optionally copy it to the clipboard. Right now, I’m considering some workarounds to achieve both actions, but they feel a bit hacky. If you have any thoughts on a clean approach to handle both actions within open, I’d really appreciate it!

**Comment by folke** [comment]
I don't get what you mean.

don't configure that `open` globally to get your url.

Just do it once.

```lua

Snacks.gitbrowse.open({open = function(url)Snacks.notify (url) end})
```

**Comment by folke** [comment]
lik this:

```lua
local function get_url()
  local ret
  Snacks.gitbrowse.open({open = function(url)
    ret = url
  end})
  return ret
end
```

**Comment by folke** [comment]
That second option wont work when there's more than one remote.
Just use the first option, as a callback

**Comment by nsoufian** [comment]
@folke thanks for help , i did miss the `Snacks.gitbrowse.open` opts , i'm now able to copy the url using :
```lua
snacks.gitbrowse.open({
  open = function(url)
    vim.fn.setreg('+', url)
    vim.notify('Yanked url to clipboard')
  end,
})
```
