### ISSUE TITLE
bug: can't open float terminal <c-/> on lazyvim 13.

### ISSUE THREAD

**Issue by DwcksDinh** [folke/snacks.nvim#59]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows 11

### Describe the bug

I can't open  float terminal when updated lazyvim 13.x, previous version have no problem

### Steps To Reproduce

1. Open lazyvim
2. Click button "L" +"U" to update lazyvim
3. Restart it and i can't open float terminal (normal terminal can work fine)
![Untitled](https://github.com/user-attachments/assets/4f4245c0-666b-4ad3-b2c6-84f75b73d954)

### Expected Behavior

Can use <c-/> like normal

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I think this should now be fixed.
Would be great if you could confirm, since I don't do Windows.

**Comment by DwcksDinh** [comment]
Yeah you fixed that, thank you so much my man.

**Comment by folke** [comment]
There's another related issue I'm trying to solve.

Can you give me the exact output of `:=vim.o.shell`?

**Comment by DwcksDinh** [comment]
Sure my man, here is my `vim.o.shell` :

```
"C:\\Users\\corcl\\AppData\\Local\\Programs\\nu\\bin\\nu.exe"
```

**Comment by folke** [comment]
I just pushed an update to fix that other issue. Can you verify everything still works for you as well?

**Comment by DwcksDinh** [comment]
> I just pushed an update to fix that other issue. Can you verify everything still works for you as well?

It still works for me
