### ISSUE TITLE
bug: Can't change SnacksBackdrop

### ISSUE THREAD

**Issue by rachartier** [folke/snacks.nvim#7]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1082+g3688a33354

### Operating system/version

WSL2 Ubuntu 22.04

### Describe the bug

Hi,
Thank you so much for this new plugin!

I have a small issue: I can't seem to change the highlight for SnacksBackdrop. I've tried setting it via Catppuccin, and via `vim.api.nvim_set_hl` in the plugin's config.

Looking at the source, SnacksBackdrop is defined here: https://github.com/folke/snacks.nvim/blob/e9d1137b90960b2d91d1ab067fabbb64e41de73a/lua/snacks/win.lua#L118

But I don't know why I can't overwrite it.

Do you have any idea?

### Steps To Reproduce

1. Add `vim.api.nvim_set_hl(0, "SnacksBackdrop", { bg = "#0000FF", default = true })` in `config`
2. Test

### Expected Behavior

To have backdrop to be changed to the desired color

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
`vim.api.nvim_set_hl(0, "SnacksBackdrop", { bg = "#0000FF", default = true }) `
That's not correct, you need to remove the `default`

**Comment by rachartier** [comment]
Sorry, a copy/paste error. I've tried without too, same issue

**Comment by folke** [comment]
SnacksBackdrop is not for notifications. Tnat's the hl group do dim the complete window when using lazygit for example.

I just realized there's no docs on hl group yet, but you can check https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/groups/snacks.lua to see what's available

**Comment by rachartier** [comment]
Thank you a lot.
That's quite some work to find what to modify but I've managed to make it look like I wanted.

For future readers, here's my setup with Catppuccin:

![image](https://github.com/user-attachments/assets/f7821277-e2c9-48c5-9c77-3ae3b75add56)


```lua
local signs = require("config.ui.signs").full_diagnostic

return {
	"folke/snacks.nvim",
	priority = 900,
	lazy = false,
	enabled = true,
	keys = {},
	opts = {
		styles = {
			notification = {
				border = require("config.ui.border").default_border,
				wo = {
					winblend = 0,
				},
			},
		},
		statuscol = {
			left = { "mark", "sign" },
			right = { "git" },
			folds = {
				open = false, -- show open fold icons
				git_hl = false, -- use Git Signs hl for fold icons
			},
			git = {
				patterns = { "GitSign", "MiniDiffSign" },
			},
			refresh = 50,
		},
		notifier = {
			icons = {
				error = signs.error,
				warn = signs.warning,
				info = signs.info,
				trace = signs.hint,
			},
		},
		lazygit = { enabled = false },
		terminal = { enabled = false },
	},
	config = function(_, opts)
		local c = require("theme").get_colors()
		local util = require("utils")

		local bg = c.base
		local amount = 1

		local hl = {
			SnacksNotifierError = { fg = c.text, bg = bg },
			SnacksNotifierBorderError = { fg = util.blend_bg(c.red, amount), bg = bg },
			SnacksNotifierIconError = { fg = c.red, bg = bg },
			SnacksNotifierTitleError = { fg = c.red, bg = bg },
			SnacksNotifierInfo = { fg = c.text, bg = bg },
			SnacksNotifierBorderInfo = { fg = util.blend_bg(c.blue, amount), bg = bg },
			SnacksNotifierIconInfo = { fg = c.blue },
			SnacksNotifierTitleInfo = { fg = c.blue },
			SnacksNotifierTrace = { fg = c.text, bg = bg },
			SnacksNotifierBorderTrace = { fg = util.blend_bg(c.cyan, amount), bg = bg },
			SnacksNotifierIconTrace = { fg = c.cyan },
			SnacksNotifierTitleTrace = { fg = c.cyan },
			SnacksNotifierWarn = { fg = c.text, bg = bg },
			SnacksNotifierBorderWarn = { fg = util.blend_bg(c.yellow, amount), bg = bg },
			SnacksNotifierIconWarn = { fg = c.yellow },
			SnacksNotifierTitleWarn = { fg = c.yellow },
		}

		for group, colors in pairs(hl) do
			vim.api.nvim_set_hl(0, group, colors)
		end

		require("snacks").setup(opts)
	end,
}
```
