### ISSUE TITLE
feature: add filetype and buftype ignore for statuscolumn

### ISSUE THREAD

**Issue by CnTeng** [folke/snacks.nvim#75]
### Did you check the docs?

- [X] I have read all the snacks.nvim docs

### Is your feature request related to a problem? Please describe.

Some plugins, like Neogit, modify column settings, which may conflict with statuscolumn.
And, statuscol.nvim have suck feature.

### Describe the solution you'd like

when entering a specified file type，the setup function return early
or create autocommand like
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "NeogitStatus",
  callback = function()
    vim.opt_local.statuscolumn = ""
  end,
})

```

### Describe alternatives you've considered

Add global filetype and buftype ignore for all snack

**Comment by folke** [comment]
Your autocmd is the way to go
