### ISSUE TITLE
add default level for showing notifications

### ISSUE THREAD

**Issue by folke** [folke/snacks.nvim#83]
nvim-notify [hides notifications below a configured level](https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/lua/notify/config/init.lua#L46-L47)[^1] but still shows them in the notification history[^2]

[^1]: set to `vim.log.levels.INFO` [by default](https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/lua/notify/config/init.lua#L21)
[^2]: accessible in nvim-notify with `:Notifications` and in snacks.notifier with `:lua require("snacks.notifier").show_history()`

Is it possible to copy this behavior with snacks.notifier? Since the switch to a snacks.notifier in LazyVim, I'm seeing more debug-level log messages I didn't before. Some of them are from my config and can be disabled, but others are from plugins.

_Originally posted by @baodrate in https://github.com/folke/snacks.nvim/discussions/82_

**Comment by disrupted** [comment]
> nvim-notify [hides notifications below a configured level](https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/lua/notify/config/init.lua#L46-L47)[1](#user-content-fn-1-dee1459a0a63d9c521b8e5559db95ee3) but still shows them in the notification history[2](#user-content-fn-2-dee1459a0a63d9c521b8e5559db95ee3)

I cannot figure out how to make this work the same way in Snacks.

I've configured `Snacks.notifier` like this

```lua
opts = {
    notifier = {
        enabled = true,
        level = vim.log.levels.INFO,
    },
}
```

now debug notifications are not shown. good!
But I would still like to see them in the notification history.

If I run `Snacks.notifier.show_history { filter = 'debug' }` it's empty 🤔

**Comment by kmoschcau** [comment]
I would also like to have two different levels for the actual notifications and the notification history. @folke do you want a separate issue opened for that?
