### ISSUE TITLE
bug/help(notifier): `nvim_echo` must not be called in a loop callback

### ISSUE THREAD

**Issue by kunzaatko** [folke/snacks.nvim#90]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-734+g8a2aec997 Build type: RelWithDebInfo LuaJIT 2.1.1724512491 Run "nvim -V1 -v" for more info

### Operating system/version

Linux TPad 6.11.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:57:56 +0000 x86_64 GNU/Linux

### Describe the bug

When a notification is called from a callback of a `Job` from `plenary`, I get an error
```
Error executing luv callback:
vim/_editor.lua:0: E5560: nvim_echo must not be called in a lua loop callback
stack traceback:
        [C]: in function 'nvim_echo'
        vim/_editor.lua: in function 'notify'
        /home/kunzaatko/.config/nvim/ftplugin/tex.lua:39: in function 'v'
        ...aatko/.local/share/nvim/lazy/plenary/lua/plenary/job.lua:245: in function '_shutdown'
        ...aatko/.local/share/nvim/lazy/plenary/lua/plenary/job.lua:48: in function <...aatko/.local/share/nvim/lazy/plenary/lua/plenary/job.lua:39>
```
The notification is launched by a `LaTeX` build function that uses the `Job` to run a system command defined as
```lua
    build = function()
      local buildjob = Job:new {
        command = 'tectonic',
        args = { '-X', 'build' },
        cwd = utils.tex.get_root():absolute(),
        -- TODO: on_stderror <kunzaatko>
      }
      vim.notify 'Building(tectonic): started'
      buildjob:start()
      buildjob:after(function()
        vim.notify 'Building(tectonic): finished' -- LINE # 39
      end)
      return buildjob
    end,
```
Would start a discussion since this is probably my mistake, but even the first notification i.e. `vim.notify 'Building(tectonic): started'` does not show up.

### Steps To Reproduce

1. Define a function that calls a notification as a loop callback.
2. Observe that the notification does not show up, instead after a while an error is shown.

### Expected Behavior

This has stopped working with a recent commit. It was still working if I restore the to commit from `lazy-lock.json`
```json
  "snacks.nvim": { "branch": "main", "commit": "334895c5bb2ed04f65800abaeb91ccb0487b0f1f" },
```
Expected behaviour is that the notification shows up.

**Comment by folke** [comment]
That's not the snacks notifier...
There was a breaking change in snacks where plugins are no longer enabled by default.

**Comment by kunzaatko** [comment]
Thank you for the information and for all the work that you are doing!
