### ISSUE TITLE
Notifier config not working for level

### ISSUE THREAD

**Issue by folke** [folke/snacks.nvim#93]
Followup for https://github.com/folke/snacks.nvim/discussions/82, notifier [now](https://github.com/folke/snacks.nvim/commit/ec9cfb36b1ea2b4bf21b5812791c8bfee3bcf322) filters notifications by level, but how do you set that level? The docs imply:

```lua
{
  "folke/snacks.nvim",
  ...
  opts = {
    ...
    notifier = {
      enabled = true,
      level = vim.log.levels.INFO,
    },
    ...
  },
  ...
}
```

but that doesn't seem to have any effect. If I'm following the code correctly, the config is being retrieved here, in `N.new()`:

https://github.com/folke/snacks.nvim/blob/063525196a43fd0a4a03bd67edce1b72e4f1c20b/lua/snacks/notifier.lua#L263-L271

but that is called at import:

https://github.com/folke/snacks.nvim/blob/063525196a43fd0a4a03bd67edce1b72e4f1c20b/lua/snacks/notifier.lua#L660-L661

even when editing `LazyVim/lua/lazyvim/plugins/init.lua` directly, I can't get the notifier config to apply before Notifier's `:new()` is called.

_Originally posted by @baodrate in https://github.com/folke/snacks.nvim/discussions/92_

**Comment by folke** [comment]
Just looked into this and I can't reproduce this @baodrate
Run `:checkhealth snacks` to see if anything is wrong with your config.

**Comment by baodrate** [comment]
Thank you @folke. Your suggestion helped me figure out the issue with my config.

The issue was my configuration looked like this:

```lua
return {
	{
		"folke/snacks.nvim",
		optional = true,
		opts = function(_, opts)
			vim.api.nvim_create_user_command(
				"Notifications",
				require("snacks.notifier").show_history,
				{ desc = "Show notifications history" }
			)
			opts.notifier = vim.tbl_extend("force", opts.notifier or {}, {
				level = vim.log.levels.INFO,
			})
			return opts
		end,
	},
}
```

the `require("snacks.notifier").show_history` was causing the import of `snacks.notifier` prior to snacks.nvim options being set. The fix was:

```diff
diff --git a/lua/plugins/ui.lua b/lua/plugins/ui.lua
index ddba522..31b1ac3 100644
--- a/lua/plugins/ui.lua
+++ b/lua/plugins/ui.lua
@@ -5,7 +5,10 @@ return {
 		opts = function(_, opts)
 			vim.api.nvim_create_user_command(
 				"Notifications",
-				require("snacks.notifier").show_history,
+				-- wrap in `function()` to avoid premature import
+				function()
+					require("snacks.notifier").show_history()
+				end,
 				{ desc = "Show notifications history" }
 			)
 			opts.notifier = vim.tbl_extend("force", opts.notifier or {}, {
```
