### ISSUE TITLE
bug: Snacks dashboard does not open on startup

### ISSUE THREAD

**Issue by rachartier** [folke/snacks.nvim#98]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1172+gf164e1e35c

### Operating system/version

WSL2 Ubuntu 22.04

### Describe the bug

Hello,

The dashboard plugin looks really neat, well done !

Unfortunately, I'm experiencing the same issue as a user on Reddit: I can't get "dashboard" to open at startup.  
I tried disabling plugins and changing the priority, but it still won't work.  
I can open it using `Snacks.dashboard()` in a popup.  

It's not a simple case to reproduce with the "repro.lua" file because it doesn't appear either due to the plugin setup.  
Here is where you can find Snacks in my config:   [https://github.com/rachartier/dotfiles/blob/main/.config/nvim/lua/plugins/utils/snacks.lua](https://github.com/rachartier/dotfiles/blob/main/.config/nvim/lua/plugins/utils/snacks.lua)

### Steps To Reproduce

Open nvim

### Expected Behavior

Having dashboard open at start

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by rachartier** [comment]
Ah my bad, another issue (#97) was created when I was writing this one.

**Comment by folke** [comment]
Can you update snacks, run `:checkhealth snacks` and report back with the output?
Just added a bunch of health checks to narrow down the issue

**Comment by rachartier** [comment]
Ah nice! `stdin is a pipe`:
![image](https://github.com/user-attachments/assets/8500a686-9720-4328-ad91-a25db64f6157)

**Comment by rachartier** [comment]
I'm also using tmux and zsh. But I tried without tmux and with bash, but same thing

**Comment by folke** [comment]
something is wrong in my pipe detection. Will work on a fix.
Closing in favor of that other issue.

**Comment by folke** [comment]
What I was doing was just not correct. I misread the docs on stdin-startup. Apparently that section was for GUIs that embed Neovim. 

Either way, I think I now found a proper way to check for piped stdin.

Would be great if you could confirm!

**Comment by rachartier** [comment]
Works great now, thanks !

**Comment by rachartier** [comment]
Sorry to bother you again, but does `terminal` supports "redrawing" ? Like, if I want to use tty-clock, for now, it doesn't display anything.

I can open a new issue if you want.

**Comment by folke** [comment]
You mean with a command that just keeps running?
Not right now, but easy to add.
I actually added a whole caching layer on top of running terminal commands so in most cases what you're seeing 
is cached output and the actual command never runs.

Will add something to allow for your use-case

**Comment by rachartier** [comment]
Yes exactly that.

Thanks a lot ! You rock.

**Comment by folke** [comment]
`tty-clock -s` or `cmatrix` now works as expected

**Comment by rachartier** [comment]
Yes! Works great, that was really fast, well done!

Maybe an option to remove the cursor inside the terminal? I can try to implement it if you want.

You can see the cursor moving really fast in `cmatrix` in bottom right corner (it does it too with `tty-clock`)
![cmatrix_cursor](https://github.com/user-attachments/assets/026283a2-eb19-4715-b50e-2b14d8bb5e2e)

**Comment by folke** [comment]
That's really weird, since I dont see the cursor at all.
What Neovim version are you on?

**Comment by folke** [comment]
https://github.com/user-attachments/assets/232ee76c-3ea9-4bb5-a686-8beb48bc0fb2

**Comment by rachartier** [comment]
That looks really clean yes, I will try to see where the problem comes from.

```
NVIM v0.11.0-dev-1186+g1763eddede
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
```

**Comment by folke** [comment]
Really odd, but it's something with the colorscheme.
Works fine with tokyonight, but not with catppuccin.
Will check what's happening here...

**Comment by folke** [comment]
default colorscheme also ok

**Comment by rachartier** [comment]
When I set `TermCursorNC = { bg = "None", fg = "None" },` it works great

**Comment by rachartier** [comment]
By default it is set in Catppuccin, maybe on tokyonight it's already disabled ?

**Comment by folke** [comment]
Good find. Just fixed it :)

**Comment by rachartier** [comment]
In any case, it is as beautiful as it is fast! Really impressive, well done and thanks you a lot once again
