### ISSUE TITLE
bug: Dashboard Terminal Sections remain blank

### ISSUE THREAD

**Issue by MediocreMitch** [folke/snacks.nvim#99]
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

Windows 10 Enterprise      Version	10.0.19045 Build 19045

### Describe the bug

![image](https://github.com/user-attachments/assets/0a01c6cd-6a8e-4b74-a0ae-a5a5dfe2e2e9)

When attempting to use Dashboards terminal sections nothing is displayed.

I have tried using each of the examples utilizing terminal sections as well as attempting to change the commands used and the only thing ever visible is the title.

### Steps To Reproduce

1. Enable snacks_dashboard
2. Launch nvim

### Expected Behavior

Expected to see terminal output in terminal section.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { 
                "folke/snacks.nvim",
                priority = 1000,
		lazy = false,
		opts = {
			bigfile = { enabled = true },
			quickfile = { enabled = true },
			words = { enabled = true },
			terminal = { enabled = true },
			dashboard = {
				sections = {
					{ section = "header" },
					{ icon = " ", title = "Keymaps", section = "keys", indent = 2, padding = 1 },
					{ icon = " ", title = "Recent Files", section = "recent_files", indent = 2, padding = 1 },
					{ icon = " ", title = "Projects", section = "projects", indent = 2, padding = 1 },
					{
						section = "startup",
					},
					{
						section = "terminal",
						title = "Version",
						cmd = "lua -v",
						random = 10,
						pane = 2,
						indent = 4,
						height = 30,
					},
				},
			},
		},
		init = function()
			vim.api.nvim_create_autocmd("User", {
				pattern = "VeryLazy",
				callback = function()
					-- Setup some globals for debugging (lazy-loaded)
					_G.dd = function(...)
						Snacks.debug.inspect(...)
					end
					_G.bt = function()
						Snacks.debug.backtrace()
					end
					vim.print = _G.dd -- Override print to use snacks for `:=` command

					-- Create some toggle mappings
					Snacks.toggle.treesitter():map("<leader>uT")
					Snacks.toggle.inlay_hints():map("<leader>uh")
				end,
			})
		end,
        }
  },
})
```

**Comment by MediocreMitch** [comment]
Well it seems to not be an issue with the plugin. I forgot I had set the vim term to powershell while on Windows Systems. That seems to break the `:terminal` command.
The culprit was:
```lua
if string.match(os.getenv("os"), "Window") then
	vim.cmd("set shell=pwsh")
end
```

**Comment by folke** [comment]
Figured as much. I just pushed an update that should show proper errors in this case.
